<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:variable name='logout'>Wyloguj si&#x0119;</xsl:variable>
<xsl:variable name='about'>Informacje</xsl:variable>
<xsl:variable name='msgInvalidData'>Wprowadzono niepoprawne dane</xsl:variable>
<xsl:variable name='msgInvalidData.ipv4'>Poprawny adres IPv4 sk&#x0142;ada si&#x0119; z czterech liczb (0-255) oddzielonych kropkami, np. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.netmask'>Poprawna maska sieci sk&#x0142;ada si&#x0119; z czterech liczb (0-255) oddzielonych kropkami, np. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.mac'>Poprawny adres MAC to nn:nn:nn:nn:nn:nn gdzie 'n' jest liczb&#x0105; (0-9) albo liter&#x0105; (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6'>Prawid&#x0142;owy adres IPv6 ma posta&#x0107; n:n:n:n:n:n:n:n, gdzie litery &#x201e;n&#x201d; oznaczaj&#x0105; cyfry (0-9) lub litery (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6mask'>Wprowadzono nieprawid&#x0142;owe dane</xsl:variable>
<xsl:variable name='msgInvalidData.time2'>Wprowadzony czas musi zawiera&#x0107; si&#x0119; w zakresie 1:00 do 12:59</xsl:variable>
<xsl:variable name='msgInvalidData.miltime2'>Wprowadzony czas musi zawiera&#x0107; si&#x0119; w zakresie 0:00 do 23:59</xsl:variable>
<xsl:variable name='msgNoncontiguousReorder'>Mo&#x017c;na zmieni&#x0107; kolejno&#x015b;&#x0107; wy&#x0142;&#x0105;cznie wybranych, s&#x0105;siaduj&#x0105;cych rz&#x0119;d&#x00f3;w</xsl:variable>
<xsl:variable name='msgStepHasErrors'>Kreator zawiera 1 lub wi&#x0119;cej b&#x0142;&#x0119;d&#x00f3;w</xsl:variable>
<xsl:variable name='msgTabHasErrors'>Tabulator zawiera 1 lub wi&#x0119;cej b&#x0142;&#x0119;d&#x00f3;w</xsl:variable>
<xsl:variable name='rowsperpage'>Rz&#x0119;d&#x00f3;w na stron&#x0119;</xsl:variable>
<xsl:variable name='perpage'>na stron&#x0119;</xsl:variable>
<xsl:variable name='itemsperpage'>Pozycji na stron&#x0119;</xsl:variable>
<xsl:variable name='page'>Strona</xsl:variable>
<xsl:variable name='of'>z</xsl:variable>
<xsl:variable name='go'>Przejd&#x017a;</xsl:variable>
<xsl:variable name='setall'>Zaznacz wszystkie</xsl:variable>
<xsl:variable name='clearall'>Kasuj wszystko</xsl:variable>
<xsl:variable name='undoall'>Cofnij wszystko</xsl:variable>
<xsl:variable name='sun'>Nie</xsl:variable>
<xsl:variable name='mon'>Pon</xsl:variable>
<xsl:variable name='tue'>Wto</xsl:variable>
<xsl:variable name='wed'>&#x015a;ro</xsl:variable>
<xsl:variable name='thu'>Czw</xsl:variable>
<xsl:variable name='fri'>Pi&#x0105;</xsl:variable>
<xsl:variable name='sat'>Sob</xsl:variable>
<xsl:variable name='login'>Zaloguj si&#x0119;</xsl:variable>
<xsl:variable name='submit'>Wy&#x015b;lij</xsl:variable>
<xsl:variable name='reset'>Zresetuj</xsl:variable>
<xsl:variable name='filter'>Filtr</xsl:variable>
<xsl:variable name='matchif'>Dopasuj je&#x015b;li</xsl:variable>
<xsl:variable name='matchgo'>Przejd&#x017a;</xsl:variable>
<xsl:variable name='matchclear'>Kasuj filtr</xsl:variable>
<xsl:variable name='matchcontains'>Zawiera</xsl:variable>
<xsl:variable name='matchnotcontain'>Nie zawiera</xsl:variable>
<xsl:variable name='matchstartswith'>Zaczyna od</xsl:variable>
<xsl:variable name='matchendswith'>Ko&#x0144;czy na</xsl:variable>
<xsl:variable name='matchexactly'>Jest dok&#x0142;adnie</xsl:variable>
<xsl:variable name='matchnotexactly'>Nie jest</xsl:variable>
<xsl:variable name='matchempty'>Jest pusty</xsl:variable>
<xsl:variable name='matchnotempty'>Nie jest pusty</xsl:variable>
<xsl:variable name='matchistrue'>Jest prawd&#x0105;</xsl:variable>
<xsl:variable name='matchisfalse'>Jest fa&#x0142;szem</xsl:variable>
<xsl:variable name='matchgreater'>Jest wi&#x0119;ksze ni&#x017c;</xsl:variable>
<xsl:variable name='matchgreaterequal'>Jest wi&#x0119;ksze ni&#x017c; lub r&#x00f3;wne</xsl:variable>
<xsl:variable name='matchless'>Jest mniejsze ni&#x017c;</xsl:variable>
<xsl:variable name='matchlessequal'>Jest mniejsze ni&#x017c; lub r&#x00f3;wne</xsl:variable>
<xsl:variable name='matchequal'>Jest r&#x00f3;wne</xsl:variable>
<xsl:variable name='matchnotequal'>Nie jest r&#x00f3;wne</xsl:variable>
<xsl:variable name='matchafter'>Jest po</xsl:variable>
<xsl:variable name='matchafterequal'>Jest po lub r&#x00f3;wne</xsl:variable>
<xsl:variable name='matchbefore'>Jest przed</xsl:variable>
<xsl:variable name='matchbeforeequal'>Jest przed lub r&#x00f3;wne</xsl:variable>
<xsl:variable name='sortclue'>Kliknij i sortuj</xsl:variable>
<xsl:variable name='special'>Szczeg&#x00f3;lny</xsl:variable>
<xsl:variable name='blocked'>Zablokowany dzie&#x0144;</xsl:variable>
<xsl:variable name='today'>Dzisiaj</xsl:variable>
<xsl:variable name='jan'>Sty</xsl:variable>
<xsl:variable name='feb'>Lut</xsl:variable>
<xsl:variable name='mar'>Mar</xsl:variable>
<xsl:variable name='apr'>Kwi</xsl:variable>
<xsl:variable name='may'>Maj</xsl:variable>
<xsl:variable name='jun'>Cze</xsl:variable>
<xsl:variable name='jul'>Lip</xsl:variable>
<xsl:variable name='aug'>Sie</xsl:variable>
<xsl:variable name='sep'>Wrz</xsl:variable>
<xsl:variable name='oct'>Pa&#x017a;</xsl:variable>
<xsl:variable name='nov'>Lis</xsl:variable>
<xsl:variable name='dec'>Gru</xsl:variable>
<xsl:variable name='navigation'>Nawigacja</xsl:variable>
<xsl:variable name='items'>Pozycje</xsl:variable>
<xsl:variable name='showing'>Wy&#x015b;wietlane</xsl:variable>
<xsl:variable name='back'>Wstecz</xsl:variable>
<xsl:variable name='next'>Nast&#x0119;pny</xsl:variable>
<xsl:variable name='previous'>Poprzedni</xsl:variable>
<xsl:variable name='help'>Pomoc</xsl:variable>
<xsl:variable name='cancel'>Anuluj</xsl:variable>
<xsl:variable name='ok'>OK</xsl:variable>
<xsl:variable name='movetotop'>Przycisk &#x201e;Przenie&#x015b; na pocz&#x0105;tek&#x201d; &#x2013; przesuni&#x0119;cie zaznaczonego w danym momencie elementu na g&#x00f3;r&#x0119; listy Wybrane</xsl:variable>
<xsl:variable name='movetobottom'>Przycisk &#x201e;Przenie&#x015b; na koniec&#x201d; &#x2013; przesuni&#x0119;cie zaznaczonego w danym momencie elementu na d&#x00f3;&#x0142; listy Wybrane</xsl:variable>
<xsl:variable name='moveup'>Przycisk &#x201e;Przenie&#x015b; do g&#x00f3;ry&#x201d; &#x2013; przesuni&#x0119;cie zaznaczonego w danym momencie elementu w g&#x00f3;r&#x0119; listy Wybrane</xsl:variable>
<xsl:variable name='movedown'>Przycisk &#x201e;Przenie&#x015b; w d&#x00f3;&#x0142;&#x201d; &#x2013; przesuni&#x0119;cie zaznaczonego w danym momencie elementu w d&#x00f3;&#x0142; listy Wybrane</xsl:variable>
<xsl:variable name='moveright'>Przycisk &#x201e;Zaznacz&#x201d; &#x2013; przeniesienie zaznaczonego w danym momencie elementu z okna Dost&#x0119;pne do okna Wybrane</xsl:variable>
<xsl:variable name='moveallright'>Przycisk &#x201e;Zaznacz wszystko&#x201d; &#x2013; zaznaczenie wszystkich element&#x00f3;w w oknie Dost&#x0119;pne</xsl:variable>
<xsl:variable name='moveleft'>Przycisk &#x201e;Odznacz&#x201d; &#x2013; usuni&#x0119;cie zaznaczonego w danym momencie elementu z okna Wybrane</xsl:variable>
<xsl:variable name='moveallleft'>Przycisk &#x201e;Odznacz wszystkie&#x201d; &#x2013; usuni&#x0119;cie wszystkich element&#x00f3;w z okna Wybrane</xsl:variable>
<xsl:variable name='showchoices'>Poka&#x017c; opcje</xsl:variable>
<xsl:variable name='sortascending'>Sortuj rosn&#x0105;co</xsl:variable>
<xsl:variable name='sortdescending'>Sortuj malej&#x0105;co</xsl:variable>
<xsl:variable name='scrollup'>Przewijanie w g&#x00f3;r&#x0119;</xsl:variable>
<xsl:variable name='scrolldown'>Przewijanie w d&#x00f3;&#x0142;</xsl:variable>
<xsl:variable name='expanddrawer'>Rozwi&#x0144;</xsl:variable>
<xsl:variable name='collapsedrawer'>Zwi&#x0144;</xsl:variable>
<xsl:variable name='collapsenav'>Zwi&#x0144; okno nawigacji</xsl:variable>
<xsl:variable name='expandnav'>Rozwi&#x0144; okno nawigacji</xsl:variable>
<xsl:variable name='resizenav'>Zmie&#x0144; rozmiar okna nawigacji</xsl:variable>
<xsl:variable name='resizetaskpane'>Zmie&#x0144; rozmiar panelu zadania</xsl:variable>
<xsl:variable name='spinner'>Zwi&#x0119;ksza/ zmniejsza odpowiedni&#x0105; warto&#x015b;&#x0107;</xsl:variable>
<xsl:variable name='firstpage'>Pierwsza strona</xsl:variable>
<xsl:variable name='previouspage'>Poprzednia strona</xsl:variable>
<xsl:variable name='nextpage'>Nast&#x0119;pna strona</xsl:variable>
<xsl:variable name='lastpage'>Ostatnia strona</xsl:variable>
<xsl:variable name='singlerowselection'>pojedynczy wyb&#x00f3;r rz&#x0119;du</xsl:variable>
<xsl:variable name='multiplerowselection'>wielokrotny wyb&#x00f3;r rz&#x0119;du</xsl:variable>
<xsl:variable name='allrowselection'>Zaznacz wszystkie wiersze</xsl:variable>
<xsl:variable name='increaseindentation'>Zwi&#x0119;ksz wci&#x0119;cie</xsl:variable>
<xsl:variable name='decreaseindentation'>Zmniejsz wci&#x0119;cie</xsl:variable>
<xsl:variable name='leaf'>Kartka</xsl:variable>
<xsl:variable name='expandtree'>Rozwi&#x0144; pozycj&#x0119; drzewa</xsl:variable>
<xsl:variable name='collapsetree'>Zwi&#x0144; pozycj&#x0119; drzewa</xsl:variable>
<xsl:variable name='togglepane'>Prze&#x0142;&#x0105;cz stan okna</xsl:variable>
<xsl:variable name='closepane'>Zamknij okno</xsl:variable>
<xsl:variable name='msgRequiredField'>Wymagane pole</xsl:variable>
<xsl:variable name='msgRequiredFieldsNotice'>Pola wymagane</xsl:variable>
<xsl:variable name='moveto_move'>Przeniesienie</xsl:variable>
<xsl:variable name='moveto_above'>Nad</xsl:variable>
<xsl:variable name='moveto_below'>Pod</xsl:variable>
<xsl:variable name='moveto_rownum'>Numer rz&#x0119;du</xsl:variable>
<xsl:variable name='moveto_moveto'>Przenie&#x015b; do</xsl:variable>
<xsl:variable name='applynew'>Zastosuj nowy</xsl:variable>
<xsl:variable name='emptyrow'>Brak danych do wy&#x015b;wietlenia</xsl:variable>
<xsl:variable name='more'>wi&#x0119;cej</xsl:variable>
<xsl:variable name='less'>mniej</xsl:variable>
<xsl:variable name='loading'>&#x0141;adowanie...</xsl:variable>
<xsl:variable name='moveabsolute'>Przenie&#x015b; zaznaczone do specyficznej lokalizacji</xsl:variable>
<xsl:variable name='showdatepicker'>Wy&#x015b;wietl datepicker</xsl:variable>
<xsl:variable name='showpreviousmonth'>Wy&#x015b;wietl poprzedni miesi&#x0105;c</xsl:variable>
<xsl:variable name='shownextmonth'>Wy&#x015b;wietl nast&#x0119;pny miesi&#x0105;c</xsl:variable>
<xsl:variable name='msgVerifyingLogin'>Sprawdzanie</xsl:variable>
<xsl:variable name='all'>Wszystkie</xsl:variable>
<xsl:variable name='msgReorderError'>Dany numer rz&#x0119;du nie istnieje</xsl:variable>
<xsl:variable name='currentpasswordprompt'>Wprowad&#x017a; bie&#x017c;&#x0105;ce has&#x0142;o</xsl:variable>
<xsl:variable name='newpasswordprompt'>Wprowad&#x017a; nowe has&#x0142;o</xsl:variable>
<xsl:variable name='confirmpasswordprompt'>Potwierd&#x017a; nowe has&#x0142;o</xsl:variable>
<xsl:variable name='save'>Zapisz</xsl:variable>
<xsl:variable name='newwindow'>Otw&#x00f3;rz w nowym oknie</xsl:variable>
<xsl:variable name='gettingstarted'>Pierwsze kroki</xsl:variable>
<xsl:variable name='donotshowagain'>Nie pokazuj ponownie</xsl:variable>
<xsl:variable name='companylogo'>Logo Cisco</xsl:variable>
<xsl:variable name='results'>wyniki</xsl:variable>
<xsl:variable name='editthismodule'>Edytuj ten modu&#x0142;</xsl:variable>
<xsl:variable name='remove'>Usu&#x0144;</xsl:variable>
<xsl:variable name='loginproblem'>Problemy z logowaniem?</xsl:variable>
<xsl:variable name='expandpane'>Rozwi&#x0144;</xsl:variable>
<xsl:variable name='collapsepane'>Zwi&#x0144;</xsl:variable>
<xsl:variable name='restorepane'>Przywr&#x00f3;&#x0107;</xsl:variable>
<xsl:variable name='dateselectionmonth'>Wyb&#x00f3;r daty &#x2013; miesi&#x0105;c</xsl:variable>
<xsl:variable name='dateselectionday'>Wyb&#x00f3;r daty &#x2013; dzie&#x0144;</xsl:variable>
<xsl:variable name='dateselectionyear'>Wyb&#x00f3;r daty &#x2013; rok</xsl:variable>
<xsl:variable name='timeselectionhour'>Wyb&#x00f3;r czasu &#x2013; godzina</xsl:variable>
<xsl:variable name='timeselectionminute'>Wyb&#x00f3;r czasu &#x2013; minuty</xsl:variable>
<xsl:variable name='timeselectionampm'>Wyb&#x00f3;r czasu &#x2013; rano lub po po&#x0142;udniu</xsl:variable>
<xsl:variable name='and'>i</xsl:variable>
<xsl:variable name='or'>lub</xsl:variable>
<xsl:variable name='addfilter'>Dodaj filtr</xsl:variable>
<xsl:variable name='removefilter'>Usu&#x0144; filtr</xsl:variable>
<xsl:variable name='filterrelationship'>Powi&#x0105;zanie filtru</xsl:variable>
<xsl:variable name='signin'>Zaloguj si&#x0119;</xsl:variable>
<xsl:variable name='signout'>Wyloguj</xsl:variable>
<xsl:variable name='submenu'>Podmenu</xsl:variable>
<xsl:variable name='gotopage1'>Id&#x017a; do strony 1</xsl:variable>
<xsl:variable name='gotopage2'>Id&#x017a; do strony 2</xsl:variable>
<xsl:variable name='gotopage3'>Id&#x017a; do strony 3</xsl:variable>
<xsl:variable name='gotopage4'>Id&#x017a; do strony 4</xsl:variable>
<xsl:variable name='gotopage5'>Id&#x017a; do strony 5</xsl:variable>
<xsl:variable name='gotopage6'>Id&#x017a; do strony 6</xsl:variable>
<xsl:variable name='gotopage7'>Id&#x017a; do strony 7</xsl:variable>
<xsl:variable name='gotopage8'>Id&#x017a; do strony 8</xsl:variable>
<xsl:variable name='gotopage9'>Id&#x017a; do strony 9</xsl:variable>
<xsl:variable name='gotopage10'>Id&#x017a; do strony 10</xsl:variable>
<xsl:variable name='refresh'>Od&#x015b;wie&#x017c;</xsl:variable>
<xsl:variable name='status'>Stan</xsl:variable>
<xsl:variable name='togglefilters'>W&#x0142;&#x0105;cz wy&#x015b;wietlanie filtr&#x00f3;w</xsl:variable>
<xsl:variable name='itemsselected'>wybranych element&#x00f3;w</xsl:variable>
<xsl:variable name='bulkvisible'>Wszystkie xxx widzialne wiersze s&#x0105; zaznaczone.</xsl:variable>
<xsl:variable name='bulktotal'>Zaznacz wszystkie xxx wiersze</xsl:variable>
<xsl:variable name='informationalmessage'>Informacja</xsl:variable>
<xsl:variable name='criticalerrormessage'>Komunikat o b&#x0142;&#x0119;dzie krytycznym</xsl:variable>
<xsl:variable name='errormessage'>Komunikat o b&#x0142;&#x0119;dzie</xsl:variable>
<xsl:variable name='warningmessage'>Ostrze&#x017c;enie</xsl:variable>
<xsl:variable name='successmessage'>Komunikat o sukcesie</xsl:variable>
<xsl:variable name='alert'>Alarmuj</xsl:variable>
<xsl:variable name='confirm'>Potwierd&#x017a;</xsl:variable>
<xsl:variable name='prompt'>Monituj</xsl:variable>
<xsl:variable name='yes'>Tak</xsl:variable>
<xsl:variable name='no'>Nie</xsl:variable>
<xsl:variable name='expandwindow'>Powi&#x0119;ksz okno, aby wy&#x015b;wietli&#x0107; pozosta&#x0142;e elementy</xsl:variable>
<xsl:variable name='messagenumber'>Numer wiadomo&#x015b;ci</xsl:variable>
<xsl:variable name='rssfeed'>Kana&#x0142; RSS</xsl:variable>
</xsl:stylesheet>
