<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:variable name='logout'>Logga ut</xsl:variable>
<xsl:variable name='about'>Om</xsl:variable>
<xsl:variable name='msgInvalidData'>Ogiltiga data har angetts</xsl:variable>
<xsl:variable name='msgInvalidData.ipv4'>En giltig IPv4-adress best&#x00e5;r av fyra siffror (0-255) &#x00e5;tskilda av punkter, t.ex. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.netmask'>En giltig n&#x00e4;tmask best&#x00e5;r av fyra siffror (0-255) &#x00e5;tskilda av punkter, t.ex. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.mac'>En giltig MAC-adress &#x00e4;r nn:nn:nn:nn:nn:nn d&#x00e4;r n antingen st&#x00e5;r f&#x00f6;r siffror (0-9) eller bokst&#x00e4;ver (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6'>En giltig IPv6-adress &#x00e4;r n:n:n:n:n:n:n:n d&#x00e4;r &#x201d;n&#x201d; &#x00e4;r antingen siffror (0&#x2013;9) eller bokst&#x00e4;ver (A&#x2013;F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6mask'>Ogiltiga data har angetts</xsl:variable>
<xsl:variable name='msgInvalidData.time2'>Den angivna tiden m&#x00e5;ste vara inom intervallet 1:00 till 12:59</xsl:variable>
<xsl:variable name='msgInvalidData.miltime2'>Den angivna tiden m&#x00e5;ste vara inom intervallet 0:00 till 23:59</xsl:variable>
<xsl:variable name='msgNoncontiguousReorder'>Du kan endast &#x00e4;ndra ordning p&#x00e5; valda rader som kommer efter varandra</xsl:variable>
<xsl:variable name='msgStepHasErrors'>Guiden inneh&#x00e5;ller ett eller fler fel</xsl:variable>
<xsl:variable name='msgTabHasErrors'>Flik inneh&#x00e5;ller 1 eller fler fel</xsl:variable>
<xsl:variable name='rowsperpage'>Rader per sida</xsl:variable>
<xsl:variable name='perpage'>per sida</xsl:variable>
<xsl:variable name='itemsperpage'>Objekt per sida</xsl:variable>
<xsl:variable name='page'>Sida</xsl:variable>
<xsl:variable name='of'>av</xsl:variable>
<xsl:variable name='go'>Ok</xsl:variable>
<xsl:variable name='setall'>Markera alla</xsl:variable>
<xsl:variable name='clearall'>Rensa alla</xsl:variable>
<xsl:variable name='undoall'>&#x00c5;ngra alla</xsl:variable>
<xsl:variable name='sun'>S&#x00f6;n</xsl:variable>
<xsl:variable name='mon'>M&#x00e5;n</xsl:variable>
<xsl:variable name='tue'>Tis</xsl:variable>
<xsl:variable name='wed'>Ons</xsl:variable>
<xsl:variable name='thu'>Tor</xsl:variable>
<xsl:variable name='fri'>Fre</xsl:variable>
<xsl:variable name='sat'>L&#x00f6;r</xsl:variable>
<xsl:variable name='login'>Logga in</xsl:variable>
<xsl:variable name='submit'>Skicka</xsl:variable>
<xsl:variable name='reset'>&#x00c5;terst&#x00e4;ll</xsl:variable>
<xsl:variable name='filter'>Filter</xsl:variable>
<xsl:variable name='matchif'>Matcha om</xsl:variable>
<xsl:variable name='matchgo'>Ok</xsl:variable>
<xsl:variable name='matchclear'>Rensa filter</xsl:variable>
<xsl:variable name='matchcontains'>Inneh&#x00e5;ller</xsl:variable>
<xsl:variable name='matchnotcontain'>Inneh&#x00e5;ller inte</xsl:variable>
<xsl:variable name='matchstartswith'>B&#x00f6;rjar med</xsl:variable>
<xsl:variable name='matchendswith'>Slutar med</xsl:variable>
<xsl:variable name='matchexactly'>&#x00c4;r exakt</xsl:variable>
<xsl:variable name='matchnotexactly'>&#x00c4;r inte</xsl:variable>
<xsl:variable name='matchempty'>&#x00c4;r tom</xsl:variable>
<xsl:variable name='matchnotempty'>&#x00c4;r inte tom</xsl:variable>
<xsl:variable name='matchistrue'>&#x00c4;r sant</xsl:variable>
<xsl:variable name='matchisfalse'>&#x00c4;r falskt</xsl:variable>
<xsl:variable name='matchgreater'>&#x00c4;r st&#x00f6;rre &#x00e4;n</xsl:variable>
<xsl:variable name='matchgreaterequal'>&#x00c4;r st&#x00f6;rre &#x00e4;n eller lika med</xsl:variable>
<xsl:variable name='matchless'>&#x00c4;r mindre &#x00e4;n</xsl:variable>
<xsl:variable name='matchlessequal'>&#x00c4;r mindre &#x00e4;n eller lika med</xsl:variable>
<xsl:variable name='matchequal'>&#x00c4;r lika med</xsl:variable>
<xsl:variable name='matchnotequal'>&#x00c4;r inte lika med</xsl:variable>
<xsl:variable name='matchafter'>&#x00c4;r efter</xsl:variable>
<xsl:variable name='matchafterequal'>&#x00c4;r efter eller lika med</xsl:variable>
<xsl:variable name='matchbefore'>&#x00c4;r f&#x00f6;re</xsl:variable>
<xsl:variable name='matchbeforeequal'>&#x00c4;r f&#x00f6;re eller lika med</xsl:variable>
<xsl:variable name='sortclue'>Sortera genom att klicka</xsl:variable>
<xsl:variable name='special'>Special</xsl:variable>
<xsl:variable name='blocked'>Sp&#x00e4;rrad dag</xsl:variable>
<xsl:variable name='today'>Idag</xsl:variable>
<xsl:variable name='jan'>Jan</xsl:variable>
<xsl:variable name='feb'>Feb</xsl:variable>
<xsl:variable name='mar'>Mar</xsl:variable>
<xsl:variable name='apr'>Apr</xsl:variable>
<xsl:variable name='may'>Maj</xsl:variable>
<xsl:variable name='jun'>Jun</xsl:variable>
<xsl:variable name='jul'>Jul</xsl:variable>
<xsl:variable name='aug'>Aug</xsl:variable>
<xsl:variable name='sep'>Sep</xsl:variable>
<xsl:variable name='oct'>Okt</xsl:variable>
<xsl:variable name='nov'>Nov</xsl:variable>
<xsl:variable name='dec'>Dec</xsl:variable>
<xsl:variable name='navigation'>Navigering</xsl:variable>
<xsl:variable name='items'>Poster</xsl:variable>
<xsl:variable name='showing'>Visar</xsl:variable>
<xsl:variable name='back'>Tillbaka</xsl:variable>
<xsl:variable name='next'>N&#x00e4;sta</xsl:variable>
<xsl:variable name='previous'>F&#x00f6;reg&#x00e5;ende</xsl:variable>
<xsl:variable name='help'>Hj&#x00e4;lp</xsl:variable>
<xsl:variable name='cancel'>Avbryt</xsl:variable>
<xsl:variable name='ok'>OK</xsl:variable>
<xsl:variable name='movetotop'>Flytta till toppen, knapp &#x2013; Flyttar det aktuella markerade objektet till toppen av listan med valda objekt</xsl:variable>
<xsl:variable name='movetobottom'>Flytta till botten, knapp &#x2013; Flyttar det aktuella markerade objektet till botten av listan med valda objekt</xsl:variable>
<xsl:variable name='moveup'>Flytta upp&#x00e5;t, knapp &#x2013; Flyttar upp det aktuella markerade objektet en position i listan med valda objekt</xsl:variable>
<xsl:variable name='movedown'>Flytta ned&#x00e5;t, knapp &#x2013; Flyttar ned det aktuella markerade objektet en position i listan med valda objekt</xsl:variable>
<xsl:variable name='moveright'>Flytta till valt, knapp &#x2013; &#x00d6;verf&#x00f6;r det aktuella markerade objektet fr&#x00e5;n rutan med tillg&#x00e4;ngliga objekt till rutan valt</xsl:variable>
<xsl:variable name='moveallright'>Flytta alla till valt, knapp &#x2013; Markerar alla objekt i rutan med tillg&#x00e4;ngliga objekt</xsl:variable>
<xsl:variable name='moveleft'>Ta bort fr&#x00e5;n valt &#x2013; Tar bort det aktuella markerade objektet fr&#x00e5;n rutan valt</xsl:variable>
<xsl:variable name='moveallleft'>Ta bort alla fr&#x00e5;n valt, knapp &#x2013; Tar bort alla objekt fr&#x00e5;n rutan valt</xsl:variable>
<xsl:variable name='showchoices'>Visa val</xsl:variable>
<xsl:variable name='sortascending'>Sortera stigande</xsl:variable>
<xsl:variable name='sortdescending'>Sortera fallande</xsl:variable>
<xsl:variable name='scrollup'>Rulla upp&#x00e5;t</xsl:variable>
<xsl:variable name='scrolldown'>Rulla ned&#x00e5;t</xsl:variable>
<xsl:variable name='expanddrawer'>Expandera</xsl:variable>
<xsl:variable name='collapsedrawer'>Komprimera</xsl:variable>
<xsl:variable name='collapsenav'>Komprimera navigeringsruta</xsl:variable>
<xsl:variable name='expandnav'>Expandera navigeringsruta</xsl:variable>
<xsl:variable name='resizenav'>&#x00c4;ndra storlek p&#x00e5; navigeringsruta</xsl:variable>
<xsl:variable name='resizetaskpane'>&#x00c4;ndra storlek p&#x00e5; uppgiftsf&#x00f6;nster</xsl:variable>
<xsl:variable name='spinner'>&#x00d6;ka/minska relaterat v&#x00e4;rde</xsl:variable>
<xsl:variable name='firstpage'>F&#x00f6;rsta sidan</xsl:variable>
<xsl:variable name='previouspage'>F&#x00f6;reg&#x00e5;ende sida</xsl:variable>
<xsl:variable name='nextpage'>N&#x00e4;sta sida</xsl:variable>
<xsl:variable name='lastpage'>Sista sidan</xsl:variable>
<xsl:variable name='singlerowselection'>en rad</xsl:variable>
<xsl:variable name='multiplerowselection'>flera rader</xsl:variable>
<xsl:variable name='allrowselection'>V&#x00e4;lj alla rader</xsl:variable>
<xsl:variable name='increaseindentation'>&#x00d6;ka indrag</xsl:variable>
<xsl:variable name='decreaseindentation'>Minska indrag</xsl:variable>
<xsl:variable name='leaf'>Blad</xsl:variable>
<xsl:variable name='expandtree'>Expandera tr&#x00e4;dobjekt</xsl:variable>
<xsl:variable name='collapsetree'>Komprimera tr&#x00e4;dobjekt</xsl:variable>
<xsl:variable name='togglepane'>V&#x00e4;xla status f&#x00f6;r ruta</xsl:variable>
<xsl:variable name='closepane'>St&#x00e4;ng ruta</xsl:variable>
<xsl:variable name='msgRequiredField'>Obligatoriskt f&#x00e4;lt</xsl:variable>
<xsl:variable name='msgRequiredFieldsNotice'>Obligatoriska f&#x00e4;lt</xsl:variable>
<xsl:variable name='moveto_move'>Flytta</xsl:variable>
<xsl:variable name='moveto_above'>Ovanf&#x00f6;r</xsl:variable>
<xsl:variable name='moveto_below'>Nedanf&#x00f6;r</xsl:variable>
<xsl:variable name='moveto_rownum'>Radnummer</xsl:variable>
<xsl:variable name='moveto_moveto'>Flytta till</xsl:variable>
<xsl:variable name='applynew'>Till&#x00e4;mpa ny</xsl:variable>
<xsl:variable name='emptyrow'>Inga data att visa</xsl:variable>
<xsl:variable name='more'>mer</xsl:variable>
<xsl:variable name='less'>mindre</xsl:variable>
<xsl:variable name='loading'>Laddar...</xsl:variable>
<xsl:variable name='moveabsolute'>Flytta till specifik plats</xsl:variable>
<xsl:variable name='showdatepicker'>Visa datumv&#x00e4;ljare</xsl:variable>
<xsl:variable name='showpreviousmonth'>Visa f&#x00f6;reg&#x00e5;ende m&#x00e5;nad</xsl:variable>
<xsl:variable name='shownextmonth'>Visa n&#x00e4;sta m&#x00e5;nad</xsl:variable>
<xsl:variable name='msgVerifyingLogin'>Kontrollerar</xsl:variable>
<xsl:variable name='all'>Alla</xsl:variable>
<xsl:variable name='msgReorderError'>Det angivna radnumret finns ej</xsl:variable>
<xsl:variable name='currentpasswordprompt'>Ange aktuellt l&#x00f6;senord</xsl:variable>
<xsl:variable name='newpasswordprompt'>Ange nytt l&#x00f6;senord</xsl:variable>
<xsl:variable name='confirmpasswordprompt'>Ange nytt l&#x00f6;senord igen</xsl:variable>
<xsl:variable name='save'>Spara</xsl:variable>
<xsl:variable name='newwindow'>&#x00d6;ppna i nytt f&#x00f6;nster</xsl:variable>
<xsl:variable name='gettingstarted'>B&#x00f6;rjar</xsl:variable>
<xsl:variable name='donotshowagain'>Visa inte igen</xsl:variable>
<xsl:variable name='companylogo'>Cisco-logotyp</xsl:variable>
<xsl:variable name='results'>resultat</xsl:variable>
<xsl:variable name='editthismodule'>Redigera den h&#x00e4;r modulen</xsl:variable>
<xsl:variable name='remove'>Ta bort</xsl:variable>
<xsl:variable name='loginproblem'>Har du problem med att logga in?</xsl:variable>
<xsl:variable name='expandpane'>Expandera</xsl:variable>
<xsl:variable name='collapsepane'>Komprimera</xsl:variable>
<xsl:variable name='restorepane'>&#x00c5;terst&#x00e4;ll</xsl:variable>
<xsl:variable name='dateselectionmonth'>Datumval m&#x00e5;nad</xsl:variable>
<xsl:variable name='dateselectionday'>Datumval dag</xsl:variable>
<xsl:variable name='dateselectionyear'>Datumval &#x00e5;r</xsl:variable>
<xsl:variable name='timeselectionhour'>Tidsval timma</xsl:variable>
<xsl:variable name='timeselectionminute'>Tidsval minut</xsl:variable>
<xsl:variable name='timeselectionampm'>Tidsval FM eller EM</xsl:variable>
<xsl:variable name='and'>och</xsl:variable>
<xsl:variable name='or'>eller</xsl:variable>
<xsl:variable name='addfilter'>L&#x00e4;gg till filter</xsl:variable>
<xsl:variable name='removefilter'>Ta bort filter</xsl:variable>
<xsl:variable name='filterrelationship'>Filtrera f&#x00f6;rh&#x00e5;llande</xsl:variable>
<xsl:variable name='signin'>Logga in</xsl:variable>
<xsl:variable name='signout'>Logga ut</xsl:variable>
<xsl:variable name='submenu'>Undermeny</xsl:variable>
<xsl:variable name='gotopage1'>G&#x00e5; till sidan 1</xsl:variable>
<xsl:variable name='gotopage2'>G&#x00e5; till sidan 2</xsl:variable>
<xsl:variable name='gotopage3'>G&#x00e5; till sidan 3</xsl:variable>
<xsl:variable name='gotopage4'>G&#x00e5; till sidan 4</xsl:variable>
<xsl:variable name='gotopage5'>G&#x00e5; till sidan 5</xsl:variable>
<xsl:variable name='gotopage6'>G&#x00e5; till sidan 6</xsl:variable>
<xsl:variable name='gotopage7'>G&#x00e5; till sidan 7</xsl:variable>
<xsl:variable name='gotopage8'>G&#x00e5; till sidan 8</xsl:variable>
<xsl:variable name='gotopage9'>G&#x00e5; till sidan 9</xsl:variable>
<xsl:variable name='gotopage10'>G&#x00e5; till sidan 10</xsl:variable>
<xsl:variable name='refresh'>Uppdatera</xsl:variable>
<xsl:variable name='status'>Status</xsl:variable>
<xsl:variable name='togglefilters'>V&#x00e4;xla mellan visning av filter</xsl:variable>
<xsl:variable name='itemsselected'>Objekt valda</xsl:variable>
<xsl:variable name='bulkvisible'>Alla xxx synliga rader &#x00e4;r valda.</xsl:variable>
<xsl:variable name='bulktotal'>V&#x00e4;lj alla xxx rader</xsl:variable>
<xsl:variable name='informationalmessage'>Informationsmeddelande</xsl:variable>
<xsl:variable name='criticalerrormessage'>Meddelande om allvarligt fel</xsl:variable>
<xsl:variable name='errormessage'>Felmeddelande</xsl:variable>
<xsl:variable name='warningmessage'>Varningsmeddelande</xsl:variable>
<xsl:variable name='successmessage'>Meddelande om lyckad &#x00e5;tg&#x00e4;rd</xsl:variable>
<xsl:variable name='alert'>Varning</xsl:variable>
<xsl:variable name='confirm'>Bekr&#x00e4;fta</xsl:variable>
<xsl:variable name='prompt'>Prompt</xsl:variable>
<xsl:variable name='yes'>Ja</xsl:variable>
<xsl:variable name='no'>Nej</xsl:variable>
<xsl:variable name='expandwindow'>Ut&#x00f6;ka f&#x00f6;nstret f&#x00f6;r att se fler objekt</xsl:variable>
<xsl:variable name='messagenumber'>Meddelandenummer</xsl:variable>
<xsl:variable name='rssfeed'>RSS-feed</xsl:variable>
</xsl:stylesheet>
