<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:variable name='logout'>Log ud</xsl:variable>
<xsl:variable name='about'>Om</xsl:variable>
<xsl:variable name='msgInvalidData'>Der er indtastet ugyldige data</xsl:variable>
<xsl:variable name='msgInvalidData.ipv4'>En gyldig IPv4-adresse best&#x00e5;r af fire tal (0-255) adskilt af punktummer, f.eks. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.netmask'>En gyldig netmaske best&#x00e5;r af fire tal (0-255) adskilt af punktummer, f.eks. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.mac'>En gyldig MAC-adresse er nn:nn:nn:nn:nn:nn, hvor n'erne er tal (0-9) eller bogstaver (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6'>En gyldig IPv6-adresse er n:n:n:n:n:n:n:n, hvor n'erne er enten tal (0-9) eller bogstaver (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6mask'>Der er indtastet ugyldige data</xsl:variable>
<xsl:variable name='msgInvalidData.time2'>Den indtastede tid skal v&#x00e6;re mellem 1:00 og 12:59</xsl:variable>
<xsl:variable name='msgInvalidData.miltime2'>Den indtastede tid skal v&#x00e6;re mellem 0:00 og 23:59</xsl:variable>
<xsl:variable name='msgNoncontiguousReorder'>Du kan kun &#x00e6;ndre r&#x00e6;kkef&#x00f8;lgen p&#x00e5; markerede rammer ved siden af hinanden</xsl:variable>
<xsl:variable name='msgStepHasErrors'>Guidetrinnet indeholder 1 eller flere fejl</xsl:variable>
<xsl:variable name='msgTabHasErrors'>Tabulator indeholder 1 eller flere fejl</xsl:variable>
<xsl:variable name='rowsperpage'>R&#x00e6;kker pr. side</xsl:variable>
<xsl:variable name='perpage'>pr. side</xsl:variable>
<xsl:variable name='itemsperpage'>Elementer pr. side</xsl:variable>
<xsl:variable name='page'>Side</xsl:variable>
<xsl:variable name='of'>af</xsl:variable>
<xsl:variable name='go'>S&#x00f8;g</xsl:variable>
<xsl:variable name='setall'>Marker alle</xsl:variable>
<xsl:variable name='clearall'>Ryd alle</xsl:variable>
<xsl:variable name='undoall'>Fortryd alle</xsl:variable>
<xsl:variable name='sun'>S&#x00f8;n</xsl:variable>
<xsl:variable name='mon'>Man</xsl:variable>
<xsl:variable name='tue'>Tirs</xsl:variable>
<xsl:variable name='wed'>Ons</xsl:variable>
<xsl:variable name='thu'>Tors</xsl:variable>
<xsl:variable name='fri'>Fre</xsl:variable>
<xsl:variable name='sat'>L&#x00f8;r</xsl:variable>
<xsl:variable name='login'>Log p&#x00e5;</xsl:variable>
<xsl:variable name='submit'>Send</xsl:variable>
<xsl:variable name='reset'>Nulstil</xsl:variable>
<xsl:variable name='filter'>Filter</xsl:variable>
<xsl:variable name='matchif'>Match hvis</xsl:variable>
<xsl:variable name='matchgo'>S&#x00f8;g</xsl:variable>
<xsl:variable name='matchclear'>Ryd filter</xsl:variable>
<xsl:variable name='matchcontains'>Indeholder</xsl:variable>
<xsl:variable name='matchnotcontain'>Indeholder ikke</xsl:variable>
<xsl:variable name='matchstartswith'>Starter med</xsl:variable>
<xsl:variable name='matchendswith'>Slutter med</xsl:variable>
<xsl:variable name='matchexactly'>Er pr&#x00e6;cist</xsl:variable>
<xsl:variable name='matchnotexactly'>Er ikke</xsl:variable>
<xsl:variable name='matchempty'>Er tom</xsl:variable>
<xsl:variable name='matchnotempty'>Er ikke tom</xsl:variable>
<xsl:variable name='matchistrue'>Er sand</xsl:variable>
<xsl:variable name='matchisfalse'>Er falsk</xsl:variable>
<xsl:variable name='matchgreater'>Er st&#x00f8;rre end</xsl:variable>
<xsl:variable name='matchgreaterequal'>Er st&#x00f8;rre end eller lig med</xsl:variable>
<xsl:variable name='matchless'>Er mindre end</xsl:variable>
<xsl:variable name='matchlessequal'>Er mindre end eller lig med</xsl:variable>
<xsl:variable name='matchequal'>Er lig med</xsl:variable>
<xsl:variable name='matchnotequal'>Er ikke lig med</xsl:variable>
<xsl:variable name='matchafter'>Er efter</xsl:variable>
<xsl:variable name='matchafterequal'>Er efter eller lige med</xsl:variable>
<xsl:variable name='matchbefore'>Er f&#x00f8;r</xsl:variable>
<xsl:variable name='matchbeforeequal'>Er f&#x00f8;r eller lige med</xsl:variable>
<xsl:variable name='sortclue'>Klik for at sortere</xsl:variable>
<xsl:variable name='special'>Speciel</xsl:variable>
<xsl:variable name='blocked'>Blokeret dag</xsl:variable>
<xsl:variable name='today'>I dag</xsl:variable>
<xsl:variable name='jan'>Jan</xsl:variable>
<xsl:variable name='feb'>Feb</xsl:variable>
<xsl:variable name='mar'>Mar</xsl:variable>
<xsl:variable name='apr'>Apr</xsl:variable>
<xsl:variable name='may'>Maj</xsl:variable>
<xsl:variable name='jun'>Jun</xsl:variable>
<xsl:variable name='jul'>Jul</xsl:variable>
<xsl:variable name='aug'>Aug</xsl:variable>
<xsl:variable name='sep'>Sep</xsl:variable>
<xsl:variable name='oct'>Okt</xsl:variable>
<xsl:variable name='nov'>Nov</xsl:variable>
<xsl:variable name='dec'>Dec</xsl:variable>
<xsl:variable name='navigation'>Navigation</xsl:variable>
<xsl:variable name='items'>Elementer</xsl:variable>
<xsl:variable name='showing'>Viser</xsl:variable>
<xsl:variable name='back'>Tilbage</xsl:variable>
<xsl:variable name='next'>N&#x00e6;ste</xsl:variable>
<xsl:variable name='previous'>Forrige</xsl:variable>
<xsl:variable name='help'>Hj&#x00e6;lp</xsl:variable>
<xsl:variable name='cancel'>Annuller</xsl:variable>
<xsl:variable name='ok'>OK</xsl:variable>
<xsl:variable name='movetotop'>Knappen Flyt til top - flytter det aktuelt valgte element til toppen af listen over valgte elementer</xsl:variable>
<xsl:variable name='movetobottom'>Knappen Flyt til bund - flytter det aktuelt valgte element til bunden af listen over valgte elementer</xsl:variable>
<xsl:variable name='moveup'>Knappen Flyt op - flytter det aktuelt valgte element et trin op p&#x00e5; listen over valgte elementer</xsl:variable>
<xsl:variable name='movedown'>Knappen Flyt ned - flytter det aktuelt valgte element et trin ned p&#x00e5; listen over valgte elementer</xsl:variable>
<xsl:variable name='moveright'>Knappen V&#x00e6;lg - flytter det aktuelt valgte element fra feltet Tilg&#x00e6;ngelige til feltet Valgte</xsl:variable>
<xsl:variable name='moveallright'>Knappen V&#x00e6;lg alle - v&#x00e6;lger alle elementer i feltet Tilg&#x00e6;ngeligt</xsl:variable>
<xsl:variable name='moveleft'>Knappen Frav&#x00e6;lg - frav&#x00e6;lger det aktuelt valgte element fra feltet Valgte</xsl:variable>
<xsl:variable name='moveallleft'>Knappen Frav&#x00e6;lg alle - fjerner alle elementer fra feltet Valgte</xsl:variable>
<xsl:variable name='showchoices'>Vis valg</xsl:variable>
<xsl:variable name='sortascending'>Soter stigende</xsl:variable>
<xsl:variable name='sortdescending'>Sorter faldende</xsl:variable>
<xsl:variable name='scrollup'>Rul op</xsl:variable>
<xsl:variable name='scrolldown'>Rul ned</xsl:variable>
<xsl:variable name='expanddrawer'>Udvid</xsl:variable>
<xsl:variable name='collapsedrawer'>Skjul</xsl:variable>
<xsl:variable name='collapsenav'>Skjul navigationsrude</xsl:variable>
<xsl:variable name='expandnav'>Udvid navigationsrude</xsl:variable>
<xsl:variable name='resizenav'>Tilpas st&#x00f8;rrelsen p&#x00e5; navigationspanelet</xsl:variable>
<xsl:variable name='resizetaskpane'>Tilpas opgavepanel</xsl:variable>
<xsl:variable name='spinner'>&#x00d8;ger/reducerer relateret v&#x00e6;rdi</xsl:variable>
<xsl:variable name='firstpage'>F&#x00f8;rste side</xsl:variable>
<xsl:variable name='previouspage'>Forrige side</xsl:variable>
<xsl:variable name='nextpage'>N&#x00e6;ste side</xsl:variable>
<xsl:variable name='lastpage'>Sidste side</xsl:variable>
<xsl:variable name='singlerowselection'>markering af enkelt r&#x00e6;kke</xsl:variable>
<xsl:variable name='multiplerowselection'>markering af flere r&#x00e6;kker</xsl:variable>
<xsl:variable name='allrowselection'>V&#x00e6;lg alle r&#x00e6;kker</xsl:variable>
<xsl:variable name='increaseindentation'>For&#x00f8;g indrykning</xsl:variable>
<xsl:variable name='decreaseindentation'>Formindsk indrykning</xsl:variable>
<xsl:variable name='leaf'>Blad</xsl:variable>
<xsl:variable name='expandtree'>Udvid tr&#x00e6;element</xsl:variable>
<xsl:variable name='collapsetree'>Skjul tr&#x00e6;element</xsl:variable>
<xsl:variable name='togglepane'>Skift status for rude</xsl:variable>
<xsl:variable name='closepane'>Luk rude</xsl:variable>
<xsl:variable name='msgRequiredField'>Obligatorisk felt</xsl:variable>
<xsl:variable name='msgRequiredFieldsNotice'>Obligatoriske felter</xsl:variable>
<xsl:variable name='moveto_move'>Flyt</xsl:variable>
<xsl:variable name='moveto_above'>Over</xsl:variable>
<xsl:variable name='moveto_below'>Under</xsl:variable>
<xsl:variable name='moveto_rownum'>R&#x00e6;kkenummer</xsl:variable>
<xsl:variable name='moveto_moveto'>Flyt til</xsl:variable>
<xsl:variable name='applynew'>Anvend ny</xsl:variable>
<xsl:variable name='emptyrow'>Ingen data at vise</xsl:variable>
<xsl:variable name='more'>mere</xsl:variable>
<xsl:variable name='less'>mindre</xsl:variable>
<xsl:variable name='loading'>Indl&#x00e6;ser</xsl:variable>
<xsl:variable name='moveabsolute'>Flyt det valgte til et bestemt sted</xsl:variable>
<xsl:variable name='showdatepicker'>Vis datov&#x00e6;lger</xsl:variable>
<xsl:variable name='showpreviousmonth'>Vis forudg&#x00e5;ende m&#x00e5;ned</xsl:variable>
<xsl:variable name='shownextmonth'>Vis f&#x00f8;lgende m&#x00e5;ned</xsl:variable>
<xsl:variable name='msgVerifyingLogin'>Verificerer</xsl:variable>
<xsl:variable name='all'>Alt</xsl:variable>
<xsl:variable name='msgReorderError'>Det angivne r&#x00e6;kkenummer findes ikke</xsl:variable>
<xsl:variable name='currentpasswordprompt'>Angiv det aktuelle password</xsl:variable>
<xsl:variable name='newpasswordprompt'>Angiv det nye password</xsl:variable>
<xsl:variable name='confirmpasswordprompt'>Genindtast det nye password</xsl:variable>
<xsl:variable name='save'>Gem</xsl:variable>
<xsl:variable name='newwindow'>&#x00c5;bn i et nyt vindue</xsl:variable>
<xsl:variable name='gettingstarted'>Kom godt i gang</xsl:variable>
<xsl:variable name='donotshowagain'>Vis det ikke igen</xsl:variable>
<xsl:variable name='companylogo'>Ciscos logo</xsl:variable>
<xsl:variable name='results'>resultater</xsl:variable>
<xsl:variable name='editthismodule'>Rediger dette modul</xsl:variable>
<xsl:variable name='remove'>Fjern</xsl:variable>
<xsl:variable name='loginproblem'>Har du problemer med at logge p&#x00e5;?</xsl:variable>
<xsl:variable name='expandpane'>Udvid</xsl:variable>
<xsl:variable name='collapsepane'>Skjul</xsl:variable>
<xsl:variable name='restorepane'>Gendan</xsl:variable>
<xsl:variable name='dateselectionmonth'>Valg af dato, m&#x00e5;ned</xsl:variable>
<xsl:variable name='dateselectionday'>Valg af dato, dag</xsl:variable>
<xsl:variable name='dateselectionyear'>Valg af dato, &#x00e5;r</xsl:variable>
<xsl:variable name='timeselectionhour'>Valg af klokkesl&#x00e6;t, time</xsl:variable>
<xsl:variable name='timeselectionminute'>Valg af klokkesl&#x00e6;t, minut</xsl:variable>
<xsl:variable name='timeselectionampm'>Valg af klokkesl&#x00e6;t, AM eller PM</xsl:variable>
<xsl:variable name='and'>og</xsl:variable>
<xsl:variable name='or'>eller</xsl:variable>
<xsl:variable name='addfilter'>Tilf&#x00f8;j filter</xsl:variable>
<xsl:variable name='removefilter'>Fjern filter</xsl:variable>
<xsl:variable name='filterrelationship'>Filterforhold</xsl:variable>
<xsl:variable name='signin'>Log ind</xsl:variable>
<xsl:variable name='signout'>Log ud</xsl:variable>
<xsl:variable name='submenu'>Undermenu</xsl:variable>
<xsl:variable name='gotopage1'>G&#x00e5; til side 1</xsl:variable>
<xsl:variable name='gotopage2'>G&#x00e5; til side 2</xsl:variable>
<xsl:variable name='gotopage3'>G&#x00e5; til side 3</xsl:variable>
<xsl:variable name='gotopage4'>G&#x00e5; til side 4</xsl:variable>
<xsl:variable name='gotopage5'>G&#x00e5; til side 5</xsl:variable>
<xsl:variable name='gotopage6'>G&#x00e5; til side 6</xsl:variable>
<xsl:variable name='gotopage7'>G&#x00e5; til side 7</xsl:variable>
<xsl:variable name='gotopage8'>G&#x00e5; til side 8</xsl:variable>
<xsl:variable name='gotopage9'>G&#x00e5; til side 9</xsl:variable>
<xsl:variable name='gotopage10'>G&#x00e5; til side 10</xsl:variable>
<xsl:variable name='refresh'>Opdater</xsl:variable>
<xsl:variable name='status'>Status</xsl:variable>
<xsl:variable name='togglefilters'>Visning af filter til og fra</xsl:variable>
<xsl:variable name='itemsselected'>elementer valgt</xsl:variable>
<xsl:variable name='bulkvisible'>Alle xxx synlige r&#x00e6;kker er valgt.</xsl:variable>
<xsl:variable name='bulktotal'>V&#x00e6;lg alle xxx r&#x00e6;kker</xsl:variable>
<xsl:variable name='informationalmessage'>Meddelelse med oplysning</xsl:variable>
<xsl:variable name='criticalerrormessage'>Meddelelse om kritisk fejl</xsl:variable>
<xsl:variable name='errormessage'>Fejlmeddelelse</xsl:variable>
<xsl:variable name='warningmessage'>Advarselsmeddelelse</xsl:variable>
<xsl:variable name='successmessage'>Meddelelse om udf&#x00f8;rt handling</xsl:variable>
<xsl:variable name='alert'>Varsel</xsl:variable>
<xsl:variable name='confirm'>Bekr&#x00e6;ft</xsl:variable>
<xsl:variable name='prompt'>Sp&#x00f8;rg</xsl:variable>
<xsl:variable name='yes'>Ja</xsl:variable>
<xsl:variable name='no'>Nej</xsl:variable>
<xsl:variable name='expandwindow'>Udvid vindue for at se ekstra elementer</xsl:variable>
<xsl:variable name='messagenumber'>Meddelelsesnummer</xsl:variable>
<xsl:variable name='rssfeed'>RSS-feed</xsl:variable>
</xsl:stylesheet>
