<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:variable name='logout'>Desconexi&#x00f3;n</xsl:variable>
<xsl:variable name='about'>Acerca de</xsl:variable>
<xsl:variable name='msgInvalidData'>Se han introducido datos incorrectos</xsl:variable>
<xsl:variable name='msgInvalidData.ipv4'>Una direcci&#x00f3;n IPv4 v&#x00e1;lida se compone de cuatro n&#x00fa;meros (0-255) separados por puntos, por ejemplo: 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.netmask'>Una m&#x00e1;scara de red v&#x00e1;lida se compone de cuatro n&#x00fa;meros (0-255) separados por puntos, por ejemplo: 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.mac'>Una direcci&#x00f3;n MAC v&#x00e1;lida es nn:nn:nn:nn:nn:nn, donde las n corresponden a d&#x00ed;gitos (0-9) o a letras (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6'>Una direcci&#x00f3;n IPv6 v&#x00e1;lida es n:n:n:n:n:n:n:n donde las &#92;&#34;n&#92;&#34; son n&#x00fa;meros (0-9) o letras (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6mask'>Se han introducido datos no v&#x00e1;lidos</xsl:variable>
<xsl:variable name='msgInvalidData.time2'>La hora introducida debe estar entre la 1:00 y las 12:59</xsl:variable>
<xsl:variable name='msgInvalidData.miltime2'>La hora introducida debe estar entre las 0:00 y las 23:59</xsl:variable>
<xsl:variable name='msgNoncontiguousReorder'>S&#x00f3;lo puede reordenar las filas seleccionadas que sean contiguas</xsl:variable>
<xsl:variable name='msgStepHasErrors'>El paso del asistente contiene uno o m&#x00e1;s errores</xsl:variable>
<xsl:variable name='msgTabHasErrors'>La pesta&#x00f1;a contiene uno o m&#x00e1;s errores</xsl:variable>
<xsl:variable name='rowsperpage'>Filas por p&#x00e1;gina</xsl:variable>
<xsl:variable name='perpage'>por p&#x00e1;gina</xsl:variable>
<xsl:variable name='itemsperpage'>Elementos por p&#x00e1;gina</xsl:variable>
<xsl:variable name='page'>P&#x00e1;gina</xsl:variable>
<xsl:variable name='of'>de</xsl:variable>
<xsl:variable name='go'>Ir</xsl:variable>
<xsl:variable name='setall'>Seleccionar todo</xsl:variable>
<xsl:variable name='clearall'>Borrar todo</xsl:variable>
<xsl:variable name='undoall'>Deshacer todo</xsl:variable>
<xsl:variable name='sun'>Dom.</xsl:variable>
<xsl:variable name='mon'>Lun.</xsl:variable>
<xsl:variable name='tue'>Mar.</xsl:variable>
<xsl:variable name='wed'>Mi&#x00e9;.</xsl:variable>
<xsl:variable name='thu'>Jue.</xsl:variable>
<xsl:variable name='fri'>Vie.</xsl:variable>
<xsl:variable name='sat'>S&#x00e1;b.</xsl:variable>
<xsl:variable name='login'>Conexi&#x00f3;n</xsl:variable>
<xsl:variable name='submit'>Enviar</xsl:variable>
<xsl:variable name='reset'>Restablecer</xsl:variable>
<xsl:variable name='filter'>Filtro</xsl:variable>
<xsl:variable name='matchif'>Coincide si</xsl:variable>
<xsl:variable name='matchgo'>Ir</xsl:variable>
<xsl:variable name='matchclear'>Borrar filtro</xsl:variable>
<xsl:variable name='matchcontains'>Contiene</xsl:variable>
<xsl:variable name='matchnotcontain'>No contiene</xsl:variable>
<xsl:variable name='matchstartswith'>Comienza por</xsl:variable>
<xsl:variable name='matchendswith'>Termina en</xsl:variable>
<xsl:variable name='matchexactly'>Es exactamente</xsl:variable>
<xsl:variable name='matchnotexactly'>No es</xsl:variable>
<xsl:variable name='matchempty'>Est&#x00e1; vac&#x00ed;o</xsl:variable>
<xsl:variable name='matchnotempty'>No est&#x00e1; vac&#x00ed;o</xsl:variable>
<xsl:variable name='matchistrue'>Es verdadero</xsl:variable>
<xsl:variable name='matchisfalse'>Es falso</xsl:variable>
<xsl:variable name='matchgreater'>Es mayor que</xsl:variable>
<xsl:variable name='matchgreaterequal'>Es mayor o igual que</xsl:variable>
<xsl:variable name='matchless'>Es menor que</xsl:variable>
<xsl:variable name='matchlessequal'>Es menor o igual que</xsl:variable>
<xsl:variable name='matchequal'>Es igual a</xsl:variable>
<xsl:variable name='matchnotequal'>No es igual a</xsl:variable>
<xsl:variable name='matchafter'>Es posterior</xsl:variable>
<xsl:variable name='matchafterequal'>Es posterior o igual a</xsl:variable>
<xsl:variable name='matchbefore'>Es anterior</xsl:variable>
<xsl:variable name='matchbeforeequal'>Es anterior o igual a</xsl:variable>
<xsl:variable name='sortclue'>Haga clic para ordenar</xsl:variable>
<xsl:variable name='special'>Especial</xsl:variable>
<xsl:variable name='blocked'>D&#x00ed;a bloqueado</xsl:variable>
<xsl:variable name='today'>Hoy</xsl:variable>
<xsl:variable name='jan'>Ene</xsl:variable>
<xsl:variable name='feb'>Feb</xsl:variable>
<xsl:variable name='mar'>Mar</xsl:variable>
<xsl:variable name='apr'>Abr</xsl:variable>
<xsl:variable name='may'>May</xsl:variable>
<xsl:variable name='jun'>Jun</xsl:variable>
<xsl:variable name='jul'>Jul</xsl:variable>
<xsl:variable name='aug'>Ago</xsl:variable>
<xsl:variable name='sep'>Sep</xsl:variable>
<xsl:variable name='oct'>Oct</xsl:variable>
<xsl:variable name='nov'>Nov</xsl:variable>
<xsl:variable name='dec'>Dic</xsl:variable>
<xsl:variable name='navigation'>Navegaci&#x00f3;n</xsl:variable>
<xsl:variable name='items'>Elementos</xsl:variable>
<xsl:variable name='showing'>Mostrando</xsl:variable>
<xsl:variable name='back'>Atr&#x00e1;s</xsl:variable>
<xsl:variable name='next'>Siguiente</xsl:variable>
<xsl:variable name='previous'>Anterior</xsl:variable>
<xsl:variable name='help'>Ayuda</xsl:variable>
<xsl:variable name='cancel'>Cancelar</xsl:variable>
<xsl:variable name='ok'>Aceptar</xsl:variable>
<xsl:variable name='movetotop'>Bot&#x00f3;n Mover a superior: mueve el elemento seleccionado en ese momento al primer lugar de la lista Seleccionados</xsl:variable>
<xsl:variable name='movetobottom'>Bot&#x00f3;n Mover a inferior: mueve el elemento seleccionado en ese momento al &#x00fa;ltimo lugar de la lista Seleccionados</xsl:variable>
<xsl:variable name='moveup'>Bot&#x00f3;n Mover arriba: mueve el elemento seleccionado en ese momento una posici&#x00f3;n hacia arriba en la lista Seleccionados</xsl:variable>
<xsl:variable name='movedown'>Bot&#x00f3;n Mover abajo: mueve el elemento seleccionado en ese momento una posici&#x00f3;n hacia abajo en la lista Seleccionados</xsl:variable>
<xsl:variable name='moveright'>Bot&#x00f3;n Seleccionar: transfiere el elemento seleccionado en ese momento desde el cuadro Disponibles al cuadro Seleccionados</xsl:variable>
<xsl:variable name='moveallright'>Bot&#x00f3;n Seleccionar todo: selecciona todos los elementos del cuadro Disponibles</xsl:variable>
<xsl:variable name='moveleft'>Bot&#x00f3;n Anular selecci&#x00f3;n: elimina el elemento seleccionado en ese momento del cuadro Seleccionados</xsl:variable>
<xsl:variable name='moveallleft'>Bot&#x00f3;n Anular la selecci&#x00f3;n de todos: elimina todos los elementos del cuadro Seleccionados</xsl:variable>
<xsl:variable name='showchoices'>Mostrar elecciones</xsl:variable>
<xsl:variable name='sortascending'>Orden ascendente</xsl:variable>
<xsl:variable name='sortdescending'>Orden descendente</xsl:variable>
<xsl:variable name='scrollup'>Desplazar hacia arriba</xsl:variable>
<xsl:variable name='scrolldown'>Desplazar hacia abajo</xsl:variable>
<xsl:variable name='expanddrawer'>Expandir</xsl:variable>
<xsl:variable name='collapsedrawer'>Contraer</xsl:variable>
<xsl:variable name='collapsenav'>Contraer panel de navegaci&#x00f3;n</xsl:variable>
<xsl:variable name='expandnav'>Expandir panel de navegaci&#x00f3;n</xsl:variable>
<xsl:variable name='resizenav'>Cambiar tama&#x00f1;o del panel de navegaci&#x00f3;n</xsl:variable>
<xsl:variable name='resizetaskpane'>Cambiar tama&#x00f1;o del panel de tareas</xsl:variable>
<xsl:variable name='spinner'>Aumenta/reduce el valor relacionado</xsl:variable>
<xsl:variable name='firstpage'>Primera p&#x00e1;gina</xsl:variable>
<xsl:variable name='previouspage'>P&#x00e1;gina anterior</xsl:variable>
<xsl:variable name='nextpage'>P&#x00e1;gina siguiente</xsl:variable>
<xsl:variable name='lastpage'>&#x00da;ltima p&#x00e1;gina</xsl:variable>
<xsl:variable name='singlerowselection'>selecci&#x00f3;n de l&#x00ed;nea &#x00fa;nica</xsl:variable>
<xsl:variable name='multiplerowselection'>selecci&#x00f3;n de varias l&#x00ed;neas</xsl:variable>
<xsl:variable name='allrowselection'>Seleccionar todas las filas</xsl:variable>
<xsl:variable name='increaseindentation'>Aumentar sangr&#x00ed;a</xsl:variable>
<xsl:variable name='decreaseindentation'>Reducir sangr&#x00ed;a</xsl:variable>
<xsl:variable name='leaf'>Hoja</xsl:variable>
<xsl:variable name='expandtree'>Expandir elemento del &#x00e1;rbol</xsl:variable>
<xsl:variable name='collapsetree'>Contraer elemento del &#x00e1;rbol</xsl:variable>
<xsl:variable name='togglepane'>Cambiar estado del panel</xsl:variable>
<xsl:variable name='closepane'>Cerrar panel</xsl:variable>
<xsl:variable name='msgRequiredField'>Campo obligatorio</xsl:variable>
<xsl:variable name='msgRequiredFieldsNotice'>Campos obligatorios</xsl:variable>
<xsl:variable name='moveto_move'>Mover</xsl:variable>
<xsl:variable name='moveto_above'>Arriba</xsl:variable>
<xsl:variable name='moveto_below'>Abajo</xsl:variable>
<xsl:variable name='moveto_rownum'>N&#x00fa;mero de fila</xsl:variable>
<xsl:variable name='moveto_moveto'>Mover a</xsl:variable>
<xsl:variable name='applynew'>Aplicar nuevo</xsl:variable>
<xsl:variable name='emptyrow'>Sin datos para mostrar</xsl:variable>
<xsl:variable name='more'>m&#x00e1;s</xsl:variable>
<xsl:variable name='less'>menos</xsl:variable>
<xsl:variable name='loading'>Cargando...</xsl:variable>
<xsl:variable name='moveabsolute'>Mover seleccionado a una ubicaci&#x00f3;n espec&#x00ed;fica</xsl:variable>
<xsl:variable name='showdatepicker'>Mostrar capturador de fecha</xsl:variable>
<xsl:variable name='showpreviousmonth'>Mostrar mes anterior</xsl:variable>
<xsl:variable name='shownextmonth'>Mostrar mes pr&#x00f3;ximo</xsl:variable>
<xsl:variable name='msgVerifyingLogin'>Comprobando</xsl:variable>
<xsl:variable name='all'>Todos</xsl:variable>
<xsl:variable name='msgReorderError'>El n&#x00fa;mero de fila especificado no existe</xsl:variable>
<xsl:variable name='currentpasswordprompt'>Introducir contrase&#x00f1;a actual</xsl:variable>
<xsl:variable name='newpasswordprompt'>Introducir contrase&#x00f1;a nueva</xsl:variable>
<xsl:variable name='confirmpasswordprompt'>Volver a introducir contrase&#x00f1;a nueva</xsl:variable>
<xsl:variable name='save'>Guardar</xsl:variable>
<xsl:variable name='newwindow'>Abrir en ventana nueva</xsl:variable>
<xsl:variable name='gettingstarted'>Comenzar</xsl:variable>
<xsl:variable name='donotshowagain'>No mostrar otra vez</xsl:variable>
<xsl:variable name='companylogo'>Logotipo de Cisco</xsl:variable>
<xsl:variable name='results'>resultados</xsl:variable>
<xsl:variable name='editthismodule'>Editar este m&#x00f3;dulo</xsl:variable>
<xsl:variable name='remove'>Quitar</xsl:variable>
<xsl:variable name='loginproblem'>&#x00bf;Problemas de conexi&#x00f3;n?</xsl:variable>
<xsl:variable name='expandpane'>Expandir</xsl:variable>
<xsl:variable name='collapsepane'>Contraer</xsl:variable>
<xsl:variable name='restorepane'>Restablecer</xsl:variable>
<xsl:variable name='dateselectionmonth'>Selecci&#x00f3;n de fecha: mes</xsl:variable>
<xsl:variable name='dateselectionday'>Selecci&#x00f3;n de fecha: d&#x00ed;a</xsl:variable>
<xsl:variable name='dateselectionyear'>Selecci&#x00f3;n de fecha: a&#x00f1;o</xsl:variable>
<xsl:variable name='timeselectionhour'>Selecci&#x00f3;n de hora: hora</xsl:variable>
<xsl:variable name='timeselectionminute'>Selecci&#x00f3;n de hora: minuto</xsl:variable>
<xsl:variable name='timeselectionampm'>Selecci&#x00f3;n de hora: AM o PM</xsl:variable>
<xsl:variable name='and'>y</xsl:variable>
<xsl:variable name='or'>o</xsl:variable>
<xsl:variable name='addfilter'>A&#x00f1;adir filtro</xsl:variable>
<xsl:variable name='removefilter'>Eliminar filtro</xsl:variable>
<xsl:variable name='filterrelationship'>Filtrar relaci&#x00f3;n</xsl:variable>
<xsl:variable name='signin'>Iniciar sesi&#x00f3;n</xsl:variable>
<xsl:variable name='signout'>Cerrar sesi&#x00f3;n</xsl:variable>
<xsl:variable name='submenu'>Submen&#x00fa;</xsl:variable>
<xsl:variable name='gotopage1'>Ir a la p&#x00e1;gina 1</xsl:variable>
<xsl:variable name='gotopage2'>Ir a la p&#x00e1;gina 2</xsl:variable>
<xsl:variable name='gotopage3'>Ir a la p&#x00e1;gina 3</xsl:variable>
<xsl:variable name='gotopage4'>Ir a la p&#x00e1;gina 4</xsl:variable>
<xsl:variable name='gotopage5'>Ir a la p&#x00e1;gina 5</xsl:variable>
<xsl:variable name='gotopage6'>Ir a la p&#x00e1;gina 6</xsl:variable>
<xsl:variable name='gotopage7'>Ir a la p&#x00e1;gina 7</xsl:variable>
<xsl:variable name='gotopage8'>Ir a la p&#x00e1;gina 8</xsl:variable>
<xsl:variable name='gotopage9'>Ir a la p&#x00e1;gina 9</xsl:variable>
<xsl:variable name='gotopage10'>Ir a la p&#x00e1;gina 10</xsl:variable>
<xsl:variable name='refresh'>Actualizar</xsl:variable>
<xsl:variable name='status'>Estado</xsl:variable>
<xsl:variable name='togglefilters'>Cambiar vista de filtros</xsl:variable>
<xsl:variable name='itemsselected'>elementos seleccionados</xsl:variable>
<xsl:variable name='bulkvisible'>Todas las filas xxx visibles est&#x00e1;n seleccionadas.</xsl:variable>
<xsl:variable name='bulktotal'>Seleccionar todas las filas xxx</xsl:variable>
<xsl:variable name='informationalmessage'>Mensaje de informaci&#x00f3;n</xsl:variable>
<xsl:variable name='criticalerrormessage'>Mensaje de error cr&#x00ed;tico</xsl:variable>
<xsl:variable name='errormessage'>Mensaje de error</xsl:variable>
<xsl:variable name='warningmessage'>Mensaje de advertencia</xsl:variable>
<xsl:variable name='successmessage'>Mensaje de operaci&#x00f3;n correcta</xsl:variable>
<xsl:variable name='alert'>Alerta</xsl:variable>
<xsl:variable name='confirm'>Confirmar</xsl:variable>
<xsl:variable name='prompt'>Solicitar</xsl:variable>
<xsl:variable name='yes'>S&#x00ed;</xsl:variable>
<xsl:variable name='no'>No</xsl:variable>
<xsl:variable name='expandwindow'>Expandir ventana para ver elementos adicionales</xsl:variable>
<xsl:variable name='messagenumber'>N&#x00fa;mero de mensaje</xsl:variable>
<xsl:variable name='rssfeed'>Fuente RSS</xsl:variable>
</xsl:stylesheet>
