<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:variable name='logout'>Log Out</xsl:variable>
<xsl:variable name='about'>About</xsl:variable>
<xsl:variable name='msgInvalidData'>Invalid data has been entered</xsl:variable>
<xsl:variable name='msgInvalidData.ipv4'>A valid IPv4 address consists of four numbers (0-255) separated by periods, e.g. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.netmask'>A valid netmask consists of four numbers (0-255) separated by periods, e.g. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.mac'>A valid MAC address is nn:nn:nn:nn:nn:nn where the 'n's are either digits (0-9) or letters (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6'>A valid IPv6 address is n:n:n:n:n:n:n:n where the 'n's are either digits (0-9) or letters (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6mask'>Invalid data has been entered</xsl:variable>
<xsl:variable name='msgInvalidData.time2'>The entered time must be in the range of 1:00 to 12:59</xsl:variable>
<xsl:variable name='msgInvalidData.miltime2'>The entered time must be in the range of 0:00 to 23:59</xsl:variable>
<xsl:variable name='msgNoncontiguousReorder'>You can only reorder selected rows that are contiguous</xsl:variable>
<xsl:variable name='msgStepHasErrors'>Wizard step contains 1 or more errors</xsl:variable>
<xsl:variable name='msgTabHasErrors'>Tab contains 1 or more errors</xsl:variable>
<xsl:variable name='rowsperpage'>Rows per page</xsl:variable>
<xsl:variable name='perpage'>per page</xsl:variable>
<xsl:variable name='itemsperpage'>Items per page</xsl:variable>
<xsl:variable name='page'>Page</xsl:variable>
<xsl:variable name='of'>of</xsl:variable>
<xsl:variable name='go'>Go</xsl:variable>
<xsl:variable name='setall'>Select All</xsl:variable>
<xsl:variable name='clearall'>Clear All</xsl:variable>
<xsl:variable name='undoall'>Undo All</xsl:variable>
<xsl:variable name='sun'>Sun</xsl:variable>
<xsl:variable name='mon'>Mon</xsl:variable>
<xsl:variable name='tue'>Tue</xsl:variable>
<xsl:variable name='wed'>Wed</xsl:variable>
<xsl:variable name='thu'>Thu</xsl:variable>
<xsl:variable name='fri'>Fri</xsl:variable>
<xsl:variable name='sat'>Sat</xsl:variable>
<xsl:variable name='login'>Log In</xsl:variable>
<xsl:variable name='submit'>Submit</xsl:variable>
<xsl:variable name='reset'>Reset</xsl:variable>
<xsl:variable name='filter'>Filter</xsl:variable>
<xsl:variable name='matchif'>Match if</xsl:variable>
<xsl:variable name='matchgo'>Go</xsl:variable>
<xsl:variable name='matchclear'>Clear Filter</xsl:variable>
<xsl:variable name='matchcontains'>Contains</xsl:variable>
<xsl:variable name='matchnotcontain'>Doesn't contain</xsl:variable>
<xsl:variable name='matchstartswith'>Starts with</xsl:variable>
<xsl:variable name='matchendswith'>Ends with</xsl:variable>
<xsl:variable name='matchexactly'>Is exactly</xsl:variable>
<xsl:variable name='matchnotexactly'>Is not</xsl:variable>
<xsl:variable name='matchempty'>Is empty</xsl:variable>
<xsl:variable name='matchnotempty'>Is not empty</xsl:variable>
<xsl:variable name='matchistrue'>Is true</xsl:variable>
<xsl:variable name='matchisfalse'>Is false</xsl:variable>
<xsl:variable name='matchgreater'>Is greater than</xsl:variable>
<xsl:variable name='matchgreaterequal'>Is greater than or equal to</xsl:variable>
<xsl:variable name='matchless'>Is less than</xsl:variable>
<xsl:variable name='matchlessequal'>Is less than or equal to</xsl:variable>
<xsl:variable name='matchequal'>Is equal to</xsl:variable>
<xsl:variable name='matchnotequal'>Is not equal to</xsl:variable>
<xsl:variable name='matchafter'>Is after</xsl:variable>
<xsl:variable name='matchafterequal'>Is after or equal to</xsl:variable>
<xsl:variable name='matchbefore'>Is before</xsl:variable>
<xsl:variable name='matchbeforeequal'>Is before or equal to</xsl:variable>
<xsl:variable name='sortclue'>Click to sort</xsl:variable>
<xsl:variable name='special'>Special</xsl:variable>
<xsl:variable name='blocked'>Blocked Day</xsl:variable>
<xsl:variable name='today'>Today</xsl:variable>
<xsl:variable name='jan'>Jan</xsl:variable>
<xsl:variable name='feb'>Feb</xsl:variable>
<xsl:variable name='mar'>Mar</xsl:variable>
<xsl:variable name='apr'>Apr</xsl:variable>
<xsl:variable name='may'>May</xsl:variable>
<xsl:variable name='jun'>Jun</xsl:variable>
<xsl:variable name='jul'>Jul</xsl:variable>
<xsl:variable name='aug'>Aug</xsl:variable>
<xsl:variable name='sep'>Sep</xsl:variable>
<xsl:variable name='oct'>Oct</xsl:variable>
<xsl:variable name='nov'>Nov</xsl:variable>
<xsl:variable name='dec'>Dec</xsl:variable>
<xsl:variable name='navigation'>Navigation</xsl:variable>
<xsl:variable name='items'>Items</xsl:variable>
<xsl:variable name='showing'>Showing</xsl:variable>
<xsl:variable name='back'>Back</xsl:variable>
<xsl:variable name='next'>Next</xsl:variable>
<xsl:variable name='previous'>Previous</xsl:variable>
<xsl:variable name='help'>Help</xsl:variable>
<xsl:variable name='cancel'>Cancel</xsl:variable>
<xsl:variable name='ok'>OK</xsl:variable>
<xsl:variable name='movetotop'>Move to Top Button - Moves the currently-selected item to the top of the Selected List</xsl:variable>
<xsl:variable name='movetobottom'>Move to Bottom Button - Moves the currently selected item to the end of the Selected List</xsl:variable>
<xsl:variable name='moveup'>Move Up Button - Moves the currently-selected item up one position in the Selected List</xsl:variable>
<xsl:variable name='movedown'>Move Down Button - Moves the currently-selected item down one position in the Selected List</xsl:variable>
<xsl:variable name='moveright'>Select Button - Transfers the currently-selected item from the Available Box to the Selected Box</xsl:variable>
<xsl:variable name='moveallright'>Select All Button - selects all the items in the Available Box</xsl:variable>
<xsl:variable name='moveleft'>Unselect Button - Removes the currently-selected item from the Selected Box</xsl:variable>
<xsl:variable name='moveallleft'>Unselect All Button - Removes all items from the Selected Box</xsl:variable>
<xsl:variable name='showchoices'>Show choices</xsl:variable>
<xsl:variable name='sortascending'>Sort ascending</xsl:variable>
<xsl:variable name='sortdescending'>Sort descending</xsl:variable>
<xsl:variable name='scrollup'>Scroll up</xsl:variable>
<xsl:variable name='scrolldown'>Scroll down</xsl:variable>
<xsl:variable name='expanddrawer'>Expand</xsl:variable>
<xsl:variable name='collapsedrawer'>Collapse</xsl:variable>
<xsl:variable name='collapsenav'>Collapse Navigation Pane</xsl:variable>
<xsl:variable name='expandnav'>Expand Navigation Pane</xsl:variable>
<xsl:variable name='resizenav'>Resize Navigation Pane</xsl:variable>
<xsl:variable name='resizetaskpane'>Resize Task Pane</xsl:variable>
<xsl:variable name='spinner'>Increases/decreases related value</xsl:variable>
<xsl:variable name='firstpage'>First page</xsl:variable>
<xsl:variable name='previouspage'>Previous page</xsl:variable>
<xsl:variable name='nextpage'>Next page</xsl:variable>
<xsl:variable name='lastpage'>Last page</xsl:variable>
<xsl:variable name='singlerowselection'>Select/unselect the row</xsl:variable>
<xsl:variable name='multiplerowselection'>Select/unselect the row</xsl:variable>
<xsl:variable name='allrowselection'>Select all rows</xsl:variable>
<xsl:variable name='increaseindentation'>Increase indentation</xsl:variable>
<xsl:variable name='decreaseindentation'>Decrease indentation</xsl:variable>
<xsl:variable name='leaf'>Leaf</xsl:variable>
<xsl:variable name='expandtree'>Expand tree item</xsl:variable>
<xsl:variable name='collapsetree'>Collapse tree item</xsl:variable>
<xsl:variable name='togglepane'>Toggle state of pane</xsl:variable>
<xsl:variable name='closepane'>Close pane</xsl:variable>
<xsl:variable name='msgRequiredField'>Required Field</xsl:variable>
<xsl:variable name='msgRequiredFieldsNotice'>Required fields</xsl:variable>
<xsl:variable name='moveto_move'>Move</xsl:variable>
<xsl:variable name='moveto_above'>Above</xsl:variable>
<xsl:variable name='moveto_below'>Below</xsl:variable>
<xsl:variable name='moveto_rownum'>Row number</xsl:variable>
<xsl:variable name='moveto_moveto'>Move to</xsl:variable>
<xsl:variable name='applynew'>Apply new</xsl:variable>
<xsl:variable name='emptyrow'>No data to display</xsl:variable>
<xsl:variable name='more'>more</xsl:variable>
<xsl:variable name='less'>less</xsl:variable>
<xsl:variable name='loading'>Loading...</xsl:variable>
<xsl:variable name='moveabsolute'>Move selected to specific location</xsl:variable>
<xsl:variable name='showdatepicker'>Display datepicker</xsl:variable>
<xsl:variable name='showpreviousmonth'>Display previous month</xsl:variable>
<xsl:variable name='shownextmonth'>Display next month</xsl:variable>
<xsl:variable name='msgVerifyingLogin'>Verifying</xsl:variable>
<xsl:variable name='all'>All</xsl:variable>
<xsl:variable name='msgReorderError'>The specified row number does not exist</xsl:variable>
<xsl:variable name='currentpasswordprompt'>Enter Current Password</xsl:variable>
<xsl:variable name='newpasswordprompt'>Enter New Password</xsl:variable>
<xsl:variable name='confirmpasswordprompt'>Re-Enter New Password</xsl:variable>
<xsl:variable name='save'>Save</xsl:variable>
<xsl:variable name='newwindow'>Open in new window</xsl:variable>
<xsl:variable name='gettingstarted'>Getting Started</xsl:variable>
<xsl:variable name='donotshowagain'>Don't show this on start-up</xsl:variable>
<xsl:variable name='companylogo'>Cisco logo</xsl:variable>
<xsl:variable name='results'>results</xsl:variable>
<xsl:variable name='editthismodule'>Edit this module</xsl:variable>
<xsl:variable name='remove'>Remove</xsl:variable>
<xsl:variable name='loginproblem'>Problems logging in?</xsl:variable>
<xsl:variable name='expandpane'>Expand</xsl:variable>
<xsl:variable name='collapsepane'>Collapse</xsl:variable>
<xsl:variable name='restorepane'>Restore</xsl:variable>
<xsl:variable name='dateselectionmonth'>Date selection month</xsl:variable>
<xsl:variable name='dateselectionday'>Date selection day</xsl:variable>
<xsl:variable name='dateselectionyear'>Date selection year</xsl:variable>
<xsl:variable name='timeselectionhour'>Time selection hour</xsl:variable>
<xsl:variable name='timeselectionminute'>Time selection minute</xsl:variable>
<xsl:variable name='timeselectionampm'>Time selection AM or PM</xsl:variable>
<xsl:variable name='and'>and</xsl:variable>
<xsl:variable name='or'>or</xsl:variable>
<xsl:variable name='addfilter'>Add filter</xsl:variable>
<xsl:variable name='removefilter'>Remove filter</xsl:variable>
<xsl:variable name='filterrelationship'>Filter relationship</xsl:variable>
<xsl:variable name='signin'>Sign In</xsl:variable>
<xsl:variable name='signout'>Sign Out</xsl:variable>
<xsl:variable name='submenu'>Sub-menu</xsl:variable>
<xsl:variable name='gotopage1'>Go to page 1</xsl:variable>
<xsl:variable name='gotopage2'>Go to page 2</xsl:variable>
<xsl:variable name='gotopage3'>Go to page 3</xsl:variable>
<xsl:variable name='gotopage4'>Go to page 4</xsl:variable>
<xsl:variable name='gotopage5'>Go to page 5</xsl:variable>
<xsl:variable name='gotopage6'>Go to page 6</xsl:variable>
<xsl:variable name='gotopage7'>Go to page 7</xsl:variable>
<xsl:variable name='gotopage8'>Go to page 8</xsl:variable>
<xsl:variable name='gotopage9'>Go to page 9</xsl:variable>
<xsl:variable name='gotopage10'>Go to page 10</xsl:variable>
<xsl:variable name='refresh'>Refresh</xsl:variable>
<xsl:variable name='status'>Status</xsl:variable>
<xsl:variable name='togglefilters'>Toggle display of filters</xsl:variable>
<xsl:variable name='itemsselected'>items selected</xsl:variable>
<xsl:variable name='bulkvisible'>All xxx visible rows are selected.</xsl:variable>
<xsl:variable name='bulktotal'>Select all xxx rows</xsl:variable>
<xsl:variable name='informationalmessage'>Informational message</xsl:variable>
<xsl:variable name='criticalerrormessage'>Critical error message</xsl:variable>
<xsl:variable name='errormessage'>Error message</xsl:variable>
<xsl:variable name='warningmessage'>Warning message</xsl:variable>
<xsl:variable name='successmessage'>Success message</xsl:variable>
<xsl:variable name='alert'>Alert</xsl:variable>
<xsl:variable name='confirm'>Confirm</xsl:variable>
<xsl:variable name='prompt'>Prompt</xsl:variable>
<xsl:variable name='yes'>Yes</xsl:variable>
<xsl:variable name='no'>No</xsl:variable>
<xsl:variable name='expandwindow'>Expand window to see additional items</xsl:variable>
<xsl:variable name='messagenumber'>Message Number</xsl:variable>
<xsl:variable name='rssfeed'>RSS feed</xsl:variable>
<xsl:variable name='addmodules'>Add Modules</xsl:variable>
<xsl:variable name='editdashboard'>Edit Dashboard</xsl:variable>
<xsl:variable name='returndashboard'>Return to Dashboard</xsl:variable>
<xsl:variable name='managedashboard'>Manage Dashboard Modules</xsl:variable>
<xsl:variable name='layoutdashboard'>Layout and Name</xsl:variable>
<xsl:variable name='dashboardtitle'>Dashboard Title</xsl:variable>
<xsl:variable name='dashboardlayout'>Dashboard Layout</xsl:variable>
<xsl:variable name='rearrangemodules'>Rearrange Modules</xsl:variable>
<xsl:variable name='dashboardmoveleft'>Move Button - Moves the currently-selected item to the prior column</xsl:variable>
<xsl:variable name='dashboardmoveright'>Move Button - Moves the currently-selected item to the next column</xsl:variable>
<xsl:variable name='dashboardremove'>Remove Button - Removes the currently-selected item from the column</xsl:variable>
<xsl:variable name='dashboardlayout100'>Single dashboard layout</xsl:variable>
<xsl:variable name='dashboardlayout5050'>Dual dashboard layout, 50% 50% split</xsl:variable>
<xsl:variable name='dashboardlayout3070'>Dual dashboard layout, 30% 70% split</xsl:variable>
<xsl:variable name='dashboardlayout7030'>Dual dashboard layout, 70% 30% split</xsl:variable>
<xsl:variable name='dashboardlayout333333'>Triple dashboard layout, 33% 33% 33% split</xsl:variable>
<xsl:variable name='dashboardlayout255025'>Triple dashboard layout, 25% 50% 25% split</xsl:variable>
<xsl:variable name='dashboardcolumn1modules'>Dashboard column 1 modules</xsl:variable>
<xsl:variable name='dashboardcolumn2modules'>Dashboard column 2 modules</xsl:variable>
<xsl:variable name='dashboardcolumn3modules'>Dashboard column 3 modules</xsl:variable>
</xsl:stylesheet>
