<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:variable name='logout'>Desconnecta</xsl:variable>
<xsl:variable name='about'>Quant a</xsl:variable>
<xsl:variable name='msgInvalidData'>S'han introdu&#x00ef;t dades no v&#x00e0;lides</xsl:variable>
<xsl:variable name='msgInvalidData.ipv4'>Una adre&#x00e7;a IPv4 consisteix en quatre n&#x00fa;meros (0-255) separats per punts, p. ex. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.netmask'>Una m&#x00e0;scara de xarxa IPv4 consisteix en quatre n&#x00fa;meros (0-255) separats per punts, p. ex. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.mac'>Una adre&#x00e7;a MAC &#x00e9;s nn:nn:nn:nn:nn:nn on les 'n' poden ser n&#x00fa;meros (0-9) o lletres (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6'>Una adre&#x00e7;a IPv6 v&#x00e0;lida &#x00e9;s n:n:n:n:n:n:n:n on les 'n' poden ser n&#x00fa;meros (0-9) o lletres (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6mask'>S'han introdu&#x00ef;t dades no v&#x00e0;lides</xsl:variable>
<xsl:variable name='msgInvalidData.time2'>Cal que l'hora introdu&#x00ef;da sigui en l'interval de 1:00 a 12:59</xsl:variable>
<xsl:variable name='msgInvalidData.miltime2'>Cal que l'hora introdu&#x00ef;da sigui en l'interval de 0:00 a 23:59</xsl:variable>
<xsl:variable name='msgNoncontiguousReorder'>Nom&#x00e9;s podeu tornar a ordenar les files contig&#x00fc;es</xsl:variable>
<xsl:variable name='msgStepHasErrors'>El pas de l'auxiliar cont&#x00e9; 1 o m&#x00e9;s errors</xsl:variable>
<xsl:variable name='msgTabHasErrors'>La pestanya cont&#x00e9; 1 o m&#x00e9;s errors</xsl:variable>
<xsl:variable name='rowsperpage'>Files per p&#x00e0;gina</xsl:variable>
<xsl:variable name='perpage'>per p&#x00e0;gina</xsl:variable>
<xsl:variable name='itemsperpage'>Elements per p&#x00e0;gina</xsl:variable>
<xsl:variable name='page'>P&#x00e0;gina</xsl:variable>
<xsl:variable name='of'>de</xsl:variable>
<xsl:variable name='go'>Endavant</xsl:variable>
<xsl:variable name='setall'>Selecciona-ho tot</xsl:variable>
<xsl:variable name='clearall'>Esborra-ho tot</xsl:variable>
<xsl:variable name='undoall'>Desf&#x00e9;s-ho tot</xsl:variable>
<xsl:variable name='sun'>Dg.</xsl:variable>
<xsl:variable name='mon'>Dl.</xsl:variable>
<xsl:variable name='tue'>Dt.</xsl:variable>
<xsl:variable name='wed'>Dc.</xsl:variable>
<xsl:variable name='thu'>Dj.</xsl:variable>
<xsl:variable name='fri'>Dv.</xsl:variable>
<xsl:variable name='sat'>Ds.</xsl:variable>
<xsl:variable name='login'>Connecta</xsl:variable>
<xsl:variable name='submit'>Envia</xsl:variable>
<xsl:variable name='reset'>Reinicialitza</xsl:variable>
<xsl:variable name='filter'>Filtra</xsl:variable>
<xsl:variable name='matchif'>Coincid&#x00e8;ncia si</xsl:variable>
<xsl:variable name='matchgo'>Endavant</xsl:variable>
<xsl:variable name='matchclear'>Esborra el filtre</xsl:variable>
<xsl:variable name='matchcontains'>Cont&#x00e9;</xsl:variable>
<xsl:variable name='matchnotcontain'>No cont&#x00e9;</xsl:variable>
<xsl:variable name='matchstartswith'>Comen&#x00e7;a amb</xsl:variable>
<xsl:variable name='matchendswith'>Acaba amb</xsl:variable>
<xsl:variable name='matchexactly'>&#x00c9;s exactament</xsl:variable>
<xsl:variable name='matchnotexactly'>No &#x00e9;s</xsl:variable>
<xsl:variable name='matchempty'>&#x00c9;s buit</xsl:variable>
<xsl:variable name='matchnotempty'>No &#x00e9;s buit</xsl:variable>
<xsl:variable name='matchistrue'>&#x00c9;s cert</xsl:variable>
<xsl:variable name='matchisfalse'>&#x00c9;s fals</xsl:variable>
<xsl:variable name='matchgreater'>&#x00c9;s superior a</xsl:variable>
<xsl:variable name='matchgreaterequal'>&#x00c9;s superior o igual a</xsl:variable>
<xsl:variable name='matchless'>&#x00c9;s inferior a</xsl:variable>
<xsl:variable name='matchlessequal'>&#x00c9;s inferior o igual a</xsl:variable>
<xsl:variable name='matchequal'>&#x00c9;s igual a</xsl:variable>
<xsl:variable name='matchnotequal'>No &#x00e9;s igual a</xsl:variable>
<xsl:variable name='matchafter'>&#x00c9;s posterior</xsl:variable>
<xsl:variable name='matchafterequal'>&#x00c9;s posterior o igual a</xsl:variable>
<xsl:variable name='matchbefore'>&#x00c9;s anterior</xsl:variable>
<xsl:variable name='matchbeforeequal'>&#x00c9;s anterior o igual a</xsl:variable>
<xsl:variable name='sortclue'>Feu clic per ordenar</xsl:variable>
<xsl:variable name='special'>Especial</xsl:variable>
<xsl:variable name='blocked'>Dia bloquejat</xsl:variable>
<xsl:variable name='today'>Avui</xsl:variable>
<xsl:variable name='jan'>Gen.</xsl:variable>
<xsl:variable name='feb'>Feb.</xsl:variable>
<xsl:variable name='mar'>Mar&#x00e7;</xsl:variable>
<xsl:variable name='apr'>Abr.</xsl:variable>
<xsl:variable name='may'>Maig</xsl:variable>
<xsl:variable name='jun'>Juny</xsl:variable>
<xsl:variable name='jul'>Jul.</xsl:variable>
<xsl:variable name='aug'>Ago.</xsl:variable>
<xsl:variable name='sep'>Set.</xsl:variable>
<xsl:variable name='oct'>Oct.</xsl:variable>
<xsl:variable name='nov'>Nov.</xsl:variable>
<xsl:variable name='dec'>Des.</xsl:variable>
<xsl:variable name='navigation'>Navegaci&#x00f3;</xsl:variable>
<xsl:variable name='items'>Elements</xsl:variable>
<xsl:variable name='showing'>Mostrant</xsl:variable>
<xsl:variable name='back'>Enrere</xsl:variable>
<xsl:variable name='next'>Seg&#x00fc;ent</xsl:variable>
<xsl:variable name='previous'>Anterior</xsl:variable>
<xsl:variable name='help'>Ajuda</xsl:variable>
<xsl:variable name='cancel'>Anul&#x00b7;la</xsl:variable>
<xsl:variable name='ok'>D'acord</xsl:variable>
<xsl:variable name='movetotop'>Bot&#x00f3; Despla&#x00e7;a al capdamunt: despla&#x00e7;a l'element seleccionat a la part superior de la llista Seleccionats</xsl:variable>
<xsl:variable name='movetobottom'>Bot&#x00f3; Despla&#x00e7;a al capdavall: despla&#x00e7;a l'element seleccionat a la part inferior de la llista Seleccionats</xsl:variable>
<xsl:variable name='moveup'>Despla&#x00e7;a cap amunt: despla&#x00e7;a l'element seleccionat una posici&#x00f3; cap amunt a la llista Seleccionats</xsl:variable>
<xsl:variable name='movedown'>Despla&#x00e7;a cap a baix: despla&#x00e7;a l'element seleccionat una posici&#x00f3; cap a baix a la llista Seleccionats</xsl:variable>
<xsl:variable name='moveright'>Bot&#x00f3; de selecci&#x00f3;: transfereix l'element seleccionat del quadre Disponible al quadre Seleccionats</xsl:variable>
<xsl:variable name='moveallright'>Bot&#x00f3; Selecciona-ho tot: selecciona tots els elements del quadre Disponibles</xsl:variable>
<xsl:variable name='moveleft'>Bot&#x00f3; Anul&#x00b7;la selecci&#x00f3;: elimina l'element seleccionat del quadre Seleccionats</xsl:variable>
<xsl:variable name='moveallleft'>Bot&#x00f3; Anul&#x00b7;la la selecci&#x00f3; de tot: elimina tots els elements del quadre Seleccionats</xsl:variable>
<xsl:variable name='showchoices'>Mostra opcions</xsl:variable>
<xsl:variable name='sortascending'>Ordena en ordre ascendent</xsl:variable>
<xsl:variable name='sortdescending'>Ordena en ordre descendent</xsl:variable>
<xsl:variable name='scrollup'>Despla&#x00e7;a cap amunt</xsl:variable>
<xsl:variable name='scrolldown'>Despla&#x00e7;a cap avall</xsl:variable>
<xsl:variable name='expanddrawer'>Amplia</xsl:variable>
<xsl:variable name='collapsedrawer'>Redueix</xsl:variable>
<xsl:variable name='collapsenav'>Redueix tauler de navegaci&#x00f3;</xsl:variable>
<xsl:variable name='expandnav'>Amplia tauler de navegaci&#x00f3;</xsl:variable>
<xsl:variable name='resizenav'>Canvia la mida del tauler de navegaci&#x00f3;</xsl:variable>
<xsl:variable name='resizetaskpane'>Canvia la mida del tauler de tasques</xsl:variable>
<xsl:variable name='spinner'>Augmenta/disminueix el valor relacionat</xsl:variable>
<xsl:variable name='firstpage'>Primera p&#x00e0;gina</xsl:variable>
<xsl:variable name='previouspage'>P&#x00e0;gina anterior</xsl:variable>
<xsl:variable name='nextpage'>P&#x00e0;gina seg&#x00fc;ent</xsl:variable>
<xsl:variable name='lastpage'>&#x00da;ltima p&#x00e0;gina</xsl:variable>
<xsl:variable name='singlerowselection'>selecci&#x00f3; d'una fila</xsl:variable>
<xsl:variable name='multiplerowselection'>selecci&#x00f3; de diverses files</xsl:variable>
<xsl:variable name='allrowselection'>Selecciona totes les files</xsl:variable>
<xsl:variable name='increaseindentation'>Augmenta sagnat</xsl:variable>
<xsl:variable name='decreaseindentation'>Disminueix sagnat</xsl:variable>
<xsl:variable name='leaf'>Full</xsl:variable>
<xsl:variable name='expandtree'>Amplia element de l'arbre</xsl:variable>
<xsl:variable name='collapsetree'>Redueix element de l'arbre</xsl:variable>
<xsl:variable name='togglepane'>Commuta l'estat del tauler</xsl:variable>
<xsl:variable name='closepane'>Tanca el tauler</xsl:variable>
<xsl:variable name='msgRequiredField'>Camp obligatori</xsl:variable>
<xsl:variable name='msgRequiredFieldsNotice'>Camps obligatoris</xsl:variable>
<xsl:variable name='moveto_move'>Mou</xsl:variable>
<xsl:variable name='moveto_above'>Amunt</xsl:variable>
<xsl:variable name='moveto_below'>Avall</xsl:variable>
<xsl:variable name='moveto_rownum'>N&#x00fa;mero de fila</xsl:variable>
<xsl:variable name='moveto_moveto'>Despla&#x00e7;a a</xsl:variable>
<xsl:variable name='applynew'>Aplica nou</xsl:variable>
<xsl:variable name='emptyrow'>No hi ha dades per mostrar</xsl:variable>
<xsl:variable name='more'>m&#x00e9;s</xsl:variable>
<xsl:variable name='less'>menys</xsl:variable>
<xsl:variable name='loading'>S'est&#x00e0; carregant...</xsl:variable>
<xsl:variable name='moveabsolute'>Despla&#x00e7;a els elements seleccionats a una ubicaci&#x00f3; espec&#x00ed;fica</xsl:variable>
<xsl:variable name='showdatepicker'>Visualitza selector de dades</xsl:variable>
<xsl:variable name='showpreviousmonth'>Visualitza mes anterior</xsl:variable>
<xsl:variable name='shownextmonth'>Visualitza mes seg&#x00fc;ent</xsl:variable>
<xsl:variable name='msgVerifyingLogin'>S'est&#x00e0; verificant</xsl:variable>
<xsl:variable name='all'>Tots</xsl:variable>
<xsl:variable name='msgReorderError'>El n&#x00fa;mero de fila especificat no existeix</xsl:variable>
<xsl:variable name='currentpasswordprompt'>Introdu&#x00ef;u la contrasenya actual</xsl:variable>
<xsl:variable name='newpasswordprompt'>Introdu&#x00ef;u la nova contrasenya</xsl:variable>
<xsl:variable name='confirmpasswordprompt'>Torneu a introduir la nova contrasenya</xsl:variable>
<xsl:variable name='save'>Desa</xsl:variable>
<xsl:variable name='newwindow'>Obre a una finestra nova</xsl:variable>
<xsl:variable name='gettingstarted'>Introducci&#x00f3;</xsl:variable>
<xsl:variable name='donotshowagain'>No ho tornis a mostrar</xsl:variable>
<xsl:variable name='companylogo'>Logotip de Cisco</xsl:variable>
<xsl:variable name='results'>resultats</xsl:variable>
<xsl:variable name='editthismodule'>Edita aquest m&#x00f2;dul</xsl:variable>
<xsl:variable name='remove'>Elimina</xsl:variable>
<xsl:variable name='loginproblem'>Teniu problemes per connectar-vos?</xsl:variable>
<xsl:variable name='expandpane'>Amplia</xsl:variable>
<xsl:variable name='collapsepane'>Redueix</xsl:variable>
<xsl:variable name='restorepane'>Restaura</xsl:variable>
<xsl:variable name='dateselectionmonth'>Mes de selecci&#x00f3; de data</xsl:variable>
<xsl:variable name='dateselectionday'>Dia de selecci&#x00f3; de data</xsl:variable>
<xsl:variable name='dateselectionyear'>Any de selecci&#x00f3; de data</xsl:variable>
<xsl:variable name='timeselectionhour'>Hora de selecci&#x00f3; d'hora</xsl:variable>
<xsl:variable name='timeselectionminute'>Minut de selecci&#x00f3; d'hora</xsl:variable>
<xsl:variable name='timeselectionampm'>AM o PM de selecci&#x00f3; d'hora</xsl:variable>
<xsl:variable name='and'>y</xsl:variable>
<xsl:variable name='or'>o</xsl:variable>
<xsl:variable name='addfilter'>Afegeix filtre</xsl:variable>
<xsl:variable name='removefilter'>Elimina filtre</xsl:variable>
<xsl:variable name='filterrelationship'>Filtra relacions</xsl:variable>
<xsl:variable name='signin'>Inicia sessi&#x00f3;</xsl:variable>
<xsl:variable name='signout'>Finalitza sessi&#x00f3;</xsl:variable>
<xsl:variable name='submenu'>Submen&#x00fa;</xsl:variable>
<xsl:variable name='gotopage1'>V&#x00e9;s a p&#x00e0;gina 1</xsl:variable>
<xsl:variable name='gotopage2'>V&#x00e9;s a p&#x00e0;gina 2</xsl:variable>
<xsl:variable name='gotopage3'>V&#x00e9;s a p&#x00e0;gina 3</xsl:variable>
<xsl:variable name='gotopage4'>V&#x00e9;s a p&#x00e0;gina 4</xsl:variable>
<xsl:variable name='gotopage5'>V&#x00e9;s a p&#x00e0;gina 5</xsl:variable>
<xsl:variable name='gotopage6'>V&#x00e9;s a p&#x00e0;gina 6</xsl:variable>
<xsl:variable name='gotopage7'>V&#x00e9;s a p&#x00e0;gina 7</xsl:variable>
<xsl:variable name='gotopage8'>V&#x00e9;s a p&#x00e0;gina 8</xsl:variable>
<xsl:variable name='gotopage9'>V&#x00e9;s a p&#x00e0;gina 9</xsl:variable>
<xsl:variable name='gotopage10'>V&#x00e9;s a p&#x00e0;gina 10</xsl:variable>
<xsl:variable name='refresh'>Actualitza</xsl:variable>
<xsl:variable name='status'>Estat</xsl:variable>
<xsl:variable name='togglefilters'>Commuta visualitzaci&#x00f3; de filtres</xsl:variable>
<xsl:variable name='itemsselected'>elements seleccionats</xsl:variable>
<xsl:variable name='bulkvisible'>S'han seleccionat les xxx files visibles</xsl:variable>
<xsl:variable name='bulktotal'>Seleccioneu les xxx files</xsl:variable>
<xsl:variable name='informationalmessage'>Missatge d'informaci&#x00f3;</xsl:variable>
<xsl:variable name='criticalerrormessage'>Missatge d'error cr&#x00ed;tic</xsl:variable>
<xsl:variable name='errormessage'>Missatge d'error</xsl:variable>
<xsl:variable name='warningmessage'>Missatge d'advert&#x00e8;ncia</xsl:variable>
<xsl:variable name='successmessage'>Missatge d'&#x00e8;xit</xsl:variable>
<xsl:variable name='alert'>Av&#x00ed;s</xsl:variable>
<xsl:variable name='confirm'>Confirma</xsl:variable>
<xsl:variable name='prompt'>Sol&#x00b7;licitud</xsl:variable>
<xsl:variable name='yes'>S&#x00ed;</xsl:variable>
<xsl:variable name='no'>No</xsl:variable>
<xsl:variable name='expandwindow'>Amplia la finestra per veure elements addicionals</xsl:variable>
<xsl:variable name='messagenumber'>N&#x00fa;mero de missatge</xsl:variable>
<xsl:variable name='rssfeed'>Canal de continguts RSS</xsl:variable>
</xsl:stylesheet>
