<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:variable name='logout'>Afmelden</xsl:variable>
<xsl:variable name='about'>Info over</xsl:variable>
<xsl:variable name='msgInvalidData'>Ongeldige gegevens opgegeven</xsl:variable>
<xsl:variable name='msgInvalidData.ipv4'>Een geldig IPv4-adres bestaat uit vier door komma's gescheiden getallen (0-255), bijv. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.netmask'>Een geldig netwerkmasker bestaat uit vier door komma's gescheiden getallen, bijv. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.mac'>Een geldig MAC-adres is nn:nn:nn:nn:nn:nn, waarbij n voor cijfers (0-9) of letters (A-F) staat</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6'>Een geldig IPv6-adres is n:n:n:n:n:n:n:n, waarbij de 'n'-en of cijfers (0-9) of letters (A-F) zijn</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6mask'>Er zijn ongeldige gegevens ingevoerd</xsl:variable>
<xsl:variable name='msgInvalidData.time2'>De opgegeven tijd dient binnen het bereik 1:00 tot 12:59 te liggen</xsl:variable>
<xsl:variable name='msgInvalidData.miltime2'>De opgegeven tijd dient binnen het bereik 0:00 tot 23:59 te liggen</xsl:variable>
<xsl:variable name='msgNoncontiguousReorder'>U kunt alleen geselecteerde rijen opnieuw sorteren als deze aansluitend zijn</xsl:variable>
<xsl:variable name='msgStepHasErrors'>Wizardstap met 1 of meer fouten</xsl:variable>
<xsl:variable name='msgTabHasErrors'>Tabblad bevat 1 of meer fouten</xsl:variable>
<xsl:variable name='rowsperpage'>Rijen per pagina</xsl:variable>
<xsl:variable name='perpage'>per pagina</xsl:variable>
<xsl:variable name='itemsperpage'>Items per pagina</xsl:variable>
<xsl:variable name='page'>Pagina</xsl:variable>
<xsl:variable name='of'>van</xsl:variable>
<xsl:variable name='go'>Start</xsl:variable>
<xsl:variable name='setall'>Alles selecteren</xsl:variable>
<xsl:variable name='clearall'>Alles opheffen</xsl:variable>
<xsl:variable name='undoall'>Alles ongedaan maken</xsl:variable>
<xsl:variable name='sun'>Zo</xsl:variable>
<xsl:variable name='mon'>Ma</xsl:variable>
<xsl:variable name='tue'>Di</xsl:variable>
<xsl:variable name='wed'>Wo</xsl:variable>
<xsl:variable name='thu'>Do</xsl:variable>
<xsl:variable name='fri'>Vr</xsl:variable>
<xsl:variable name='sat'>Za</xsl:variable>
<xsl:variable name='login'>Aanmelden</xsl:variable>
<xsl:variable name='submit'>Indienen</xsl:variable>
<xsl:variable name='reset'>Opnieuw instellen</xsl:variable>
<xsl:variable name='filter'>Filter</xsl:variable>
<xsl:variable name='matchif'>Treffer indien</xsl:variable>
<xsl:variable name='matchgo'>Start</xsl:variable>
<xsl:variable name='matchclear'>Filteren opheffen</xsl:variable>
<xsl:variable name='matchcontains'>Bevat</xsl:variable>
<xsl:variable name='matchnotcontain'>Bevat niet</xsl:variable>
<xsl:variable name='matchstartswith'>Begint met</xsl:variable>
<xsl:variable name='matchendswith'>Eindigt met</xsl:variable>
<xsl:variable name='matchexactly'>Is precies gelijk aan</xsl:variable>
<xsl:variable name='matchnotexactly'>Is niet</xsl:variable>
<xsl:variable name='matchempty'>Is leeg</xsl:variable>
<xsl:variable name='matchnotempty'>Is niet leeg</xsl:variable>
<xsl:variable name='matchistrue'>Is waar</xsl:variable>
<xsl:variable name='matchisfalse'>Is onwaar</xsl:variable>
<xsl:variable name='matchgreater'>Is groter dan</xsl:variable>
<xsl:variable name='matchgreaterequal'>Is groter dan of gelijk aan</xsl:variable>
<xsl:variable name='matchless'>Is kleiner dan</xsl:variable>
<xsl:variable name='matchlessequal'>Is kleiner dan of gelijk aan</xsl:variable>
<xsl:variable name='matchequal'>Is gelijk aan</xsl:variable>
<xsl:variable name='matchnotequal'>Is niet gelijk aan</xsl:variable>
<xsl:variable name='matchafter'>Is na</xsl:variable>
<xsl:variable name='matchafterequal'>Is na of gelijk aan</xsl:variable>
<xsl:variable name='matchbefore'>Is voor</xsl:variable>
<xsl:variable name='matchbeforeequal'>Is voor of gelijk aan</xsl:variable>
<xsl:variable name='sortclue'>Klik om te sorteren</xsl:variable>
<xsl:variable name='special'>Speciaal</xsl:variable>
<xsl:variable name='blocked'>Dag geblokkeerd</xsl:variable>
<xsl:variable name='today'>Vandaag</xsl:variable>
<xsl:variable name='jan'>Jan</xsl:variable>
<xsl:variable name='feb'>Feb</xsl:variable>
<xsl:variable name='mar'>Mrt</xsl:variable>
<xsl:variable name='apr'>Apr</xsl:variable>
<xsl:variable name='may'>Mei</xsl:variable>
<xsl:variable name='jun'>Jun</xsl:variable>
<xsl:variable name='jul'>Jul</xsl:variable>
<xsl:variable name='aug'>Aug</xsl:variable>
<xsl:variable name='sep'>Sep</xsl:variable>
<xsl:variable name='oct'>Okt</xsl:variable>
<xsl:variable name='nov'>Nov</xsl:variable>
<xsl:variable name='dec'>Dec</xsl:variable>
<xsl:variable name='navigation'>Navigatie</xsl:variable>
<xsl:variable name='items'>Items</xsl:variable>
<xsl:variable name='showing'>Weergave</xsl:variable>
<xsl:variable name='back'>Terug</xsl:variable>
<xsl:variable name='next'>Volgende</xsl:variable>
<xsl:variable name='previous'>Vorige</xsl:variable>
<xsl:variable name='help'>Help</xsl:variable>
<xsl:variable name='cancel'>Annuleren</xsl:variable>
<xsl:variable name='ok'>OK</xsl:variable>
<xsl:variable name='movetotop'>Knop Naar boven - het geselecteerde item wordt naar de eerste positie in de geselecteerde lijst verplaatst</xsl:variable>
<xsl:variable name='movetobottom'>Knop Naar beneden - het geselecteerde item wordt naar de laatste positie in de geselecteerde lijst verplaatst</xsl:variable>
<xsl:variable name='moveup'>Knop Omhoog - het geselecteerde item wordt &#x00e9;&#x00e9;n positie omhoog in de geselecteerde lijst verplaatst</xsl:variable>
<xsl:variable name='movedown'>Knop Omlaag - het geselecteerde item wordt &#x00e9;&#x00e9;n positie omlaag in de geselecteerde lijst verplaatst</xsl:variable>
<xsl:variable name='moveright'>Knop Selecteren - het geselecteerde item wordt van het vak Beschikbaar naar het vak Geselecteerd verplaatst</xsl:variable>
<xsl:variable name='moveallright'>Knop Alles selecteren - alle items in het vak Beschikbaar worden geselecteerd</xsl:variable>
<xsl:variable name='moveleft'>Knop Selectie ongedaan maken - het geselecteerde item wordt uit het vak Geselecteerd verwijderd</xsl:variable>
<xsl:variable name='moveallleft'>Knop Gehele selectie ongedaan maken - alle items worden uit het vak Geselecteerd verwijderd</xsl:variable>
<xsl:variable name='showchoices'>Keuzes weergeven</xsl:variable>
<xsl:variable name='sortascending'>Oplopend sorteren</xsl:variable>
<xsl:variable name='sortdescending'>Aflopend sorteren</xsl:variable>
<xsl:variable name='scrollup'>Omhoog schuiven</xsl:variable>
<xsl:variable name='scrolldown'>Omlaag schuiven</xsl:variable>
<xsl:variable name='expanddrawer'>Uitvouwen</xsl:variable>
<xsl:variable name='collapsedrawer'>Samenvouwen</xsl:variable>
<xsl:variable name='collapsenav'>Navigatiedeelvenster samenvouwen</xsl:variable>
<xsl:variable name='expandnav'>Navigatiedeelvenster uitvouwen</xsl:variable>
<xsl:variable name='resizenav'>Grootte van navigatievenster wijzigen</xsl:variable>
<xsl:variable name='resizetaskpane'>Formaat taakvenster wijzigen</xsl:variable>
<xsl:variable name='spinner'>Gerelateerde waarde vergroten/verkleinen</xsl:variable>
<xsl:variable name='firstpage'>Eerste pagina</xsl:variable>
<xsl:variable name='previouspage'>Vorige pagina</xsl:variable>
<xsl:variable name='nextpage'>Volgende pagina</xsl:variable>
<xsl:variable name='lastpage'>Laatste pagina</xsl:variable>
<xsl:variable name='singlerowselection'>selectie van &#x00e9;&#x00e9;n rij</xsl:variable>
<xsl:variable name='multiplerowselection'>selectie van meerdere rijen</xsl:variable>
<xsl:variable name='allrowselection'>Alle rijen selecteren</xsl:variable>
<xsl:variable name='increaseindentation'>Inspringing vergroten</xsl:variable>
<xsl:variable name='decreaseindentation'>Inspringing verkleinen</xsl:variable>
<xsl:variable name='leaf'>Bladeren</xsl:variable>
<xsl:variable name='expandtree'>Boomstructuuritem uitvouwen</xsl:variable>
<xsl:variable name='collapsetree'>Boomstructuuritem samenvouwen</xsl:variable>
<xsl:variable name='togglepane'>Schakelen tussen deelvensters</xsl:variable>
<xsl:variable name='closepane'>Deelvenster sluiten</xsl:variable>
<xsl:variable name='msgRequiredField'>Vereist veld</xsl:variable>
<xsl:variable name='msgRequiredFieldsNotice'>Vereiste velden</xsl:variable>
<xsl:variable name='moveto_move'>Verplaatsen</xsl:variable>
<xsl:variable name='moveto_above'>Boven</xsl:variable>
<xsl:variable name='moveto_below'>Onder</xsl:variable>
<xsl:variable name='moveto_rownum'>Rijnummer</xsl:variable>
<xsl:variable name='moveto_moveto'>Verplaatsen naar</xsl:variable>
<xsl:variable name='applynew'>Nieuw toepassen</xsl:variable>
<xsl:variable name='emptyrow'>Geen data om weer te geven</xsl:variable>
<xsl:variable name='more'>meer</xsl:variable>
<xsl:variable name='less'>minder</xsl:variable>
<xsl:variable name='loading'>Laden...</xsl:variable>
<xsl:variable name='moveabsolute'>Verplaats het geselecteerde naar specifieke locatie</xsl:variable>
<xsl:variable name='showdatepicker'>Datepicker weergeven</xsl:variable>
<xsl:variable name='showpreviousmonth'>Vorige maand weergeven</xsl:variable>
<xsl:variable name='shownextmonth'>Volgende maand weergeven</xsl:variable>
<xsl:variable name='msgVerifyingLogin'>Nagaan</xsl:variable>
<xsl:variable name='all'>Alles</xsl:variable>
<xsl:variable name='msgReorderError'>Het specifieke rijnummer bestaat niet</xsl:variable>
<xsl:variable name='currentpasswordprompt'>Voer huidig wachtwoord in</xsl:variable>
<xsl:variable name='newpasswordprompt'>Voer nieuw wachtwoord in</xsl:variable>
<xsl:variable name='confirmpasswordprompt'>Voer nieuw wachtwoord opnieuw in</xsl:variable>
<xsl:variable name='save'>Opslaan</xsl:variable>
<xsl:variable name='newwindow'>In nieuw venster openen</xsl:variable>
<xsl:variable name='gettingstarted'>Aan de slag</xsl:variable>
<xsl:variable name='donotshowagain'>Niet opnieuw tonen</xsl:variable>
<xsl:variable name='companylogo'>Cisco-logo</xsl:variable>
<xsl:variable name='results'>resultaten</xsl:variable>
<xsl:variable name='editthismodule'>Deze module bewerken</xsl:variable>
<xsl:variable name='remove'>Verwijderen</xsl:variable>
<xsl:variable name='loginproblem'>Problemen bij het aanmelden?</xsl:variable>
<xsl:variable name='expandpane'>Uitvouwen</xsl:variable>
<xsl:variable name='collapsepane'>Samenvouwen</xsl:variable>
<xsl:variable name='restorepane'>Herstellen</xsl:variable>
<xsl:variable name='dateselectionmonth'>Datumselectie - maand</xsl:variable>
<xsl:variable name='dateselectionday'>Datumselectie - dag</xsl:variable>
<xsl:variable name='dateselectionyear'>Datumselectie - jaar</xsl:variable>
<xsl:variable name='timeselectionhour'>Tijdselectie - uur</xsl:variable>
<xsl:variable name='timeselectionminute'>Tijdselectie - minuut</xsl:variable>
<xsl:variable name='timeselectionampm'>Tijdselectie - AM of PM</xsl:variable>
<xsl:variable name='and'>en</xsl:variable>
<xsl:variable name='or'>of</xsl:variable>
<xsl:variable name='addfilter'>Filter toevoegen</xsl:variable>
<xsl:variable name='removefilter'>Filter verwijderen</xsl:variable>
<xsl:variable name='filterrelationship'>Relatie filters</xsl:variable>
<xsl:variable name='signin'>Aanmelden</xsl:variable>
<xsl:variable name='signout'>Afmelden</xsl:variable>
<xsl:variable name='submenu'>Submenu</xsl:variable>
<xsl:variable name='gotopage1'>Ga naar pagina 1</xsl:variable>
<xsl:variable name='gotopage2'>Ga naar pagina 2</xsl:variable>
<xsl:variable name='gotopage3'>Ga naar pagina 3</xsl:variable>
<xsl:variable name='gotopage4'>Ga naar pagina 4</xsl:variable>
<xsl:variable name='gotopage5'>Ga naar pagina 5</xsl:variable>
<xsl:variable name='gotopage6'>Ga naar pagina 6</xsl:variable>
<xsl:variable name='gotopage7'>Ga naar pagina 7</xsl:variable>
<xsl:variable name='gotopage8'>Ga naar pagina 8</xsl:variable>
<xsl:variable name='gotopage9'>Ga naar pagina 9</xsl:variable>
<xsl:variable name='gotopage10'>Ga naar pagina 10</xsl:variable>
<xsl:variable name='refresh'>Vernieuwen</xsl:variable>
<xsl:variable name='status'>Status</xsl:variable>
<xsl:variable name='togglefilters'>Weergave filters in-/uitschakelen</xsl:variable>
<xsl:variable name='itemsselected'>geselecteerde items</xsl:variable>
<xsl:variable name='bulkvisible'>Alle xxx zichtbare rijen zijn geselecteerd.</xsl:variable>
<xsl:variable name='bulktotal'>Alle xxx rijen selecteren</xsl:variable>
<xsl:variable name='informationalmessage'>Informatiebericht</xsl:variable>
<xsl:variable name='criticalerrormessage'>Melding kritieke fout</xsl:variable>
<xsl:variable name='errormessage'>Foutmelding</xsl:variable>
<xsl:variable name='warningmessage'>Waarschuwing</xsl:variable>
<xsl:variable name='successmessage'>Melding succes</xsl:variable>
<xsl:variable name='alert'>Waarschuwen</xsl:variable>
<xsl:variable name='confirm'>Bevestigen</xsl:variable>
<xsl:variable name='prompt'>Melden</xsl:variable>
<xsl:variable name='yes'>Ja</xsl:variable>
<xsl:variable name='no'>Nee</xsl:variable>
<xsl:variable name='expandwindow'>Venster uitvouwen om meer items weer te geven</xsl:variable>
<xsl:variable name='messagenumber'>Berichtnummer</xsl:variable>
<xsl:variable name='rssfeed'>RSS-feed</xsl:variable>
</xsl:stylesheet>
