<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:variable name='logout'>Fermer session</xsl:variable>
<xsl:variable name='about'>&#x00c0; propos de</xsl:variable>
<xsl:variable name='msgInvalidData'>Des donn&#x00e9;es non valides ont &#x00e9;t&#x00e9; entr&#x00e9;es.</xsl:variable>
<xsl:variable name='msgInvalidData.ipv4'>Une adresse IPv4 valide est compos&#x00e9;e de quatre nombres (0&#x00a0;&#x00e0;&#x00a0;255) s&#x00e9;par&#x00e9;s par des points, p. ex., 123.0.255.3.</xsl:variable>
<xsl:variable name='msgInvalidData.netmask'>Un masque de r&#x00e9;seau valide est compos&#x00e9; de quatre nombres (0&#x00a0;&#x00e0;&#x00a0;255) s&#x00e9;par&#x00e9;s par des points, p. ex., 123.0.255.3.</xsl:variable>
<xsl:variable name='msgInvalidData.mac'>Une adresse MAC valide est au format nn:nn:nn:nn:nn:nn o&#x00f9; les &#x00ab;&#x00a0;n&#x00a0;&#x00bb; sont soit des chiffres (0&#x00a0;&#x00e0;&#x00a0;9), soit des lettres (A&#x00a0;&#x00e0;&#x00a0;F).</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6'>Une adresse IPv6 valide est au format n:n:n:n:n:n:n:n o&#x00f9; les &#x00ab;&#x00a0;n&#x00a0;&#x00bb; sont soit des chiffres (0&#x00a0;&#x00e0;&#x00a0;9), soit des lettres (A&#x00a0;&#x00e0;&#x00a0;F).</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6mask'>Des donn&#x00e9;es non valides ont &#x00e9;t&#x00e9; entr&#x00e9;es.</xsl:variable>
<xsl:variable name='msgInvalidData.time2'>L'heure doit &#x00ea;tre comprise dans la plage 1:00&#x00a0;&#x00e0;&#x00a0;12:59.</xsl:variable>
<xsl:variable name='msgInvalidData.miltime2'>L'heure doit &#x00ea;tre comprise dans la plage 0:00&#x00a0;&#x00e0;&#x00a0;23:59.</xsl:variable>
<xsl:variable name='msgNoncontiguousReorder'>Vous ne pouvez r&#x00e9;organiser que les rang&#x00e9;es adjacentes parmi celles s&#x00e9;lectionn&#x00e9;es.</xsl:variable>
<xsl:variable name='msgStepHasErrors'>L'&#x00e9;tape de l'assistant contient une ou plusieurs erreurs.</xsl:variable>
<xsl:variable name='msgTabHasErrors'>L'onglet contient une ou plusieurs erreurs.</xsl:variable>
<xsl:variable name='rowsperpage'>Rang&#x00e9;es par page</xsl:variable>
<xsl:variable name='perpage'>par page</xsl:variable>
<xsl:variable name='itemsperpage'>&#x00c9;l&#x00e9;ments par page</xsl:variable>
<xsl:variable name='page'>Page</xsl:variable>
<xsl:variable name='of'>sur</xsl:variable>
<xsl:variable name='go'>Aller</xsl:variable>
<xsl:variable name='setall'>S&#x00e9;lectionner tout</xsl:variable>
<xsl:variable name='clearall'>Effacer tout</xsl:variable>
<xsl:variable name='undoall'>Annuler tout</xsl:variable>
<xsl:variable name='sun'>Dim</xsl:variable>
<xsl:variable name='mon'>Lun</xsl:variable>
<xsl:variable name='tue'>Mar</xsl:variable>
<xsl:variable name='wed'>Mer</xsl:variable>
<xsl:variable name='thu'>Jeu</xsl:variable>
<xsl:variable name='fri'>Ven</xsl:variable>
<xsl:variable name='sat'>Sam</xsl:variable>
<xsl:variable name='login'>Ouvrir session</xsl:variable>
<xsl:variable name='submit'>Soumettre</xsl:variable>
<xsl:variable name='reset'>R&#x00e9;initialiser</xsl:variable>
<xsl:variable name='filter'>Filtrer</xsl:variable>
<xsl:variable name='matchif'>Associer si</xsl:variable>
<xsl:variable name='matchgo'>Aller</xsl:variable>
<xsl:variable name='matchclear'>Annuler filtre</xsl:variable>
<xsl:variable name='matchcontains'>Contient</xsl:variable>
<xsl:variable name='matchnotcontain'>Ne contient pas</xsl:variable>
<xsl:variable name='matchstartswith'>Commence par</xsl:variable>
<xsl:variable name='matchendswith'>Finit par</xsl:variable>
<xsl:variable name='matchexactly'>Est exactement</xsl:variable>
<xsl:variable name='matchnotexactly'>N'est pas</xsl:variable>
<xsl:variable name='matchempty'>Est vide</xsl:variable>
<xsl:variable name='matchnotempty'>N'est pas vide</xsl:variable>
<xsl:variable name='matchistrue'>Est vrai</xsl:variable>
<xsl:variable name='matchisfalse'>Est faux</xsl:variable>
<xsl:variable name='matchgreater'>Est sup&#x00e9;rieur &#x00e0;</xsl:variable>
<xsl:variable name='matchgreaterequal'>Est sup&#x00e9;rieur ou &#x00e9;gal &#x00e0;</xsl:variable>
<xsl:variable name='matchless'>Est inf&#x00e9;rieur &#x00e0;</xsl:variable>
<xsl:variable name='matchlessequal'>Est inf&#x00e9;rieur ou &#x00e9;gal &#x00e0;</xsl:variable>
<xsl:variable name='matchequal'>Est &#x00e9;gal &#x00e0;</xsl:variable>
<xsl:variable name='matchnotequal'>N'est pas &#x00e9;gal &#x00e0;</xsl:variable>
<xsl:variable name='matchafter'>Est ult&#x00e9;rieur &#x00e0;</xsl:variable>
<xsl:variable name='matchafterequal'>Est ult&#x00e9;rieur ou &#x00e9;gal &#x00e0;</xsl:variable>
<xsl:variable name='matchbefore'>Est ant&#x00e9;rieur &#x00e0;</xsl:variable>
<xsl:variable name='matchbeforeequal'>Est ant&#x00e9;rieur ou &#x00e9;gal &#x00e0;</xsl:variable>
<xsl:variable name='sortclue'>Cliquer pour trier</xsl:variable>
<xsl:variable name='special'>Sp&#x00e9;cial</xsl:variable>
<xsl:variable name='blocked'>Jour bloqu&#x00e9;</xsl:variable>
<xsl:variable name='today'>Aujourd'hui</xsl:variable>
<xsl:variable name='jan'>Jan</xsl:variable>
<xsl:variable name='feb'>F&#x00e9;v</xsl:variable>
<xsl:variable name='mar'>Mar</xsl:variable>
<xsl:variable name='apr'>Avr</xsl:variable>
<xsl:variable name='may'>Mai</xsl:variable>
<xsl:variable name='jun'>Jun</xsl:variable>
<xsl:variable name='jul'>Jui</xsl:variable>
<xsl:variable name='aug'>Ao&#x00fb;</xsl:variable>
<xsl:variable name='sep'>Sep</xsl:variable>
<xsl:variable name='oct'>Oct</xsl:variable>
<xsl:variable name='nov'>Nov</xsl:variable>
<xsl:variable name='dec'>D&#x00e9;c</xsl:variable>
<xsl:variable name='navigation'>Navigation</xsl:variable>
<xsl:variable name='items'>&#x00c9;l&#x00e9;ments</xsl:variable>
<xsl:variable name='showing'>Affich&#x00e9;</xsl:variable>
<xsl:variable name='back'>Retour</xsl:variable>
<xsl:variable name='next'>Suivant</xsl:variable>
<xsl:variable name='previous'>Pr&#x00e9;c&#x00e9;dent</xsl:variable>
<xsl:variable name='help'>Aide</xsl:variable>
<xsl:variable name='cancel'>Annuler</xsl:variable>
<xsl:variable name='ok'>OK</xsl:variable>
<xsl:variable name='movetotop'>Bouton D&#x00e9;placer au d&#x00e9;but&#x00a0;&#x2013; D&#x00e9;place l'&#x00e9;l&#x00e9;ment s&#x00e9;lectionn&#x00e9; au d&#x00e9;but de la liste</xsl:variable>
<xsl:variable name='movetobottom'>Bouton D&#x00e9;placer &#x00e0; la fin&#x00a0;&#x2013; D&#x00e9;place l'&#x00e9;l&#x00e9;ment s&#x00e9;lectionn&#x00e9; &#x00e0; la fin de la liste</xsl:variable>
<xsl:variable name='moveup'>Bouton D&#x00e9;placer vers le haut&#x00a0;&#x2013; D&#x00e9;place l'&#x00e9;l&#x00e9;ment s&#x00e9;lectionn&#x00e9; d'une ligne vers le haut de la liste</xsl:variable>
<xsl:variable name='movedown'>Bouton D&#x00e9;placer vers le bas&#x00a0;&#x2013; D&#x00e9;place l'&#x00e9;l&#x00e9;ment s&#x00e9;lectionn&#x00e9; d'une ligne vers le bas de la liste</xsl:variable>
<xsl:variable name='moveright'>Bouton S&#x00e9;lectionner&#x00a0;&#x2013; Transf&#x00e8;re l'&#x00e9;l&#x00e9;ment s&#x00e9;lectionn&#x00e9; de la bo&#x00ee;te Disponible &#x00e0; la bo&#x00ee;te S&#x00e9;lectionn&#x00e9;</xsl:variable>
<xsl:variable name='moveallright'>Bouton S&#x00e9;lectionner tout&#x00a0;&#x2013; S&#x00e9;lectionne tous les &#x00e9;l&#x00e9;ments de la bo&#x00ee;te Disponible</xsl:variable>
<xsl:variable name='moveleft'>Bouton D&#x00e9;s&#x00e9;lectionner&#x00a0;&#x2013; Retire l'&#x00e9;l&#x00e9;ment s&#x00e9;lectionn&#x00e9; de la bo&#x00ee;te S&#x00e9;lectionn&#x00e9;</xsl:variable>
<xsl:variable name='moveallleft'>Bouton D&#x00e9;s&#x00e9;lectionner tout&#x00a0;&#x2013; Retire tous les &#x00e9;l&#x00e9;ments de la bo&#x00ee;te S&#x00e9;lectionn&#x00e9;</xsl:variable>
<xsl:variable name='showchoices'>Afficher les choix</xsl:variable>
<xsl:variable name='sortascending'>Tri croissant</xsl:variable>
<xsl:variable name='sortdescending'>Tri d&#x00e9;croissant</xsl:variable>
<xsl:variable name='scrollup'>D&#x00e9;filer vers le haut</xsl:variable>
<xsl:variable name='scrolldown'>D&#x00e9;filer vers le bas</xsl:variable>
<xsl:variable name='expanddrawer'>Agrandir</xsl:variable>
<xsl:variable name='collapsedrawer'>R&#x00e9;duire</xsl:variable>
<xsl:variable name='collapsenav'>R&#x00e9;duire la fen&#x00ea;tre de navigation</xsl:variable>
<xsl:variable name='expandnav'>Agrandir la fen&#x00ea;tre de navigation</xsl:variable>
<xsl:variable name='resizenav'>Redimensionner la fen&#x00ea;tre de navigation</xsl:variable>
<xsl:variable name='resizetaskpane'>Redimensionner la fen&#x00ea;tre de t&#x00e2;che</xsl:variable>
<xsl:variable name='spinner'>Augmente/diminue la valeur associ&#x00e9;e</xsl:variable>
<xsl:variable name='firstpage'>Premi&#x00e8;re page</xsl:variable>
<xsl:variable name='previouspage'>Page pr&#x00e9;c&#x00e9;dente</xsl:variable>
<xsl:variable name='nextpage'>Page suivante</xsl:variable>
<xsl:variable name='lastpage'>Derni&#x00e8;re page</xsl:variable>
<xsl:variable name='singlerowselection'>s&#x00e9;lection d'une rang&#x00e9;e</xsl:variable>
<xsl:variable name='multiplerowselection'>s&#x00e9;lection de plusieurs rang&#x00e9;es</xsl:variable>
<xsl:variable name='allrowselection'>S&#x00e9;lectionner toutes les rang&#x00e9;es</xsl:variable>
<xsl:variable name='increaseindentation'>Augmenter le retrait</xsl:variable>
<xsl:variable name='decreaseindentation'>Diminuer le retrait</xsl:variable>
<xsl:variable name='leaf'>N&#x0153;ud terminal</xsl:variable>
<xsl:variable name='expandtree'>D&#x00e9;velopper l'&#x00e9;l&#x00e9;ment de l'arborescence</xsl:variable>
<xsl:variable name='collapsetree'>R&#x00e9;duire l'&#x00e9;l&#x00e9;ment de l'arborescence</xsl:variable>
<xsl:variable name='togglepane'>Changer l'&#x00e9;tat de la fen&#x00ea;tre</xsl:variable>
<xsl:variable name='closepane'>Fermer la fen&#x00ea;tre</xsl:variable>
<xsl:variable name='msgRequiredField'>Champ obligatoire</xsl:variable>
<xsl:variable name='msgRequiredFieldsNotice'>Champs obligatoires</xsl:variable>
<xsl:variable name='moveto_move'>D&#x00e9;placer</xsl:variable>
<xsl:variable name='moveto_above'>Au-dessus</xsl:variable>
<xsl:variable name='moveto_below'>En dessous</xsl:variable>
<xsl:variable name='moveto_rownum'>Num&#x00e9;ro de la rang&#x00e9;e</xsl:variable>
<xsl:variable name='moveto_moveto'>D&#x00e9;placer vers</xsl:variable>
<xsl:variable name='applynew'>Appliquer nouveau</xsl:variable>
<xsl:variable name='emptyrow'>Aucune donn&#x00e9;e &#x00e0; afficher</xsl:variable>
<xsl:variable name='more'>plus</xsl:variable>
<xsl:variable name='less'>moins</xsl:variable>
<xsl:variable name='loading'>Chargement...</xsl:variable>
<xsl:variable name='moveabsolute'>D&#x00e9;placer la s&#x00e9;lection vers un emplacement sp&#x00e9;cifique</xsl:variable>
<xsl:variable name='showdatepicker'>Afficher le s&#x00e9;lecteur de date</xsl:variable>
<xsl:variable name='showpreviousmonth'>Afficher le mois pr&#x00e9;c&#x00e9;dent</xsl:variable>
<xsl:variable name='shownextmonth'>Afficher le mois suivant</xsl:variable>
<xsl:variable name='msgVerifyingLogin'>V&#x00e9;rification</xsl:variable>
<xsl:variable name='all'>Tout</xsl:variable>
<xsl:variable name='msgReorderError'>Le num&#x00e9;ro de rang&#x00e9;e indiqu&#x00e9; n'existe pas.</xsl:variable>
<xsl:variable name='currentpasswordprompt'>Mot de passe actuel</xsl:variable>
<xsl:variable name='newpasswordprompt'>Nouveau mot de passe</xsl:variable>
<xsl:variable name='confirmpasswordprompt'>Confirmation du nouveau mot de passe</xsl:variable>
<xsl:variable name='save'>Enregistrer</xsl:variable>
<xsl:variable name='newwindow'>Ouvrir dans une nouvelle fen&#x00ea;tre</xsl:variable>
<xsl:variable name='gettingstarted'>Mise en route</xsl:variable>
<xsl:variable name='donotshowagain'>Ne plus afficher</xsl:variable>
<xsl:variable name='companylogo'>Logo Cisco</xsl:variable>
<xsl:variable name='results'>r&#x00e9;sultats</xsl:variable>
<xsl:variable name='editthismodule'>Modifier ce module</xsl:variable>
<xsl:variable name='remove'>Supprimer</xsl:variable>
<xsl:variable name='loginproblem'>Probl&#x00e8;mes d'ouverture de session?</xsl:variable>
<xsl:variable name='expandpane'>Agrandir</xsl:variable>
<xsl:variable name='collapsepane'>R&#x00e9;duire</xsl:variable>
<xsl:variable name='restorepane'>Restaurer</xsl:variable>
<xsl:variable name='dateselectionmonth'>Mois de la s&#x00e9;lection</xsl:variable>
<xsl:variable name='dateselectionday'>Jour de la s&#x00e9;lection</xsl:variable>
<xsl:variable name='dateselectionyear'>Ann&#x00e9;e de la s&#x00e9;lection</xsl:variable>
<xsl:variable name='timeselectionhour'>Heure de la s&#x00e9;lection</xsl:variable>
<xsl:variable name='timeselectionminute'>Minute de la s&#x00e9;lection</xsl:variable>
<xsl:variable name='timeselectionampm'>Format AM ou PM de la s&#x00e9;lection</xsl:variable>
<xsl:variable name='and'>et</xsl:variable>
<xsl:variable name='or'>ou</xsl:variable>
<xsl:variable name='addfilter'>Ajouter filtre</xsl:variable>
<xsl:variable name='removefilter'>Supprimer filtre</xsl:variable>
<xsl:variable name='filterrelationship'>Filtrer relation</xsl:variable>
<xsl:variable name='signin'>Connexion</xsl:variable>
<xsl:variable name='signout'>D&#x00e9;connexion</xsl:variable>
<xsl:variable name='submenu'>Sous-menu</xsl:variable>
<xsl:variable name='gotopage1'>Aller &#x00e0; la page 1</xsl:variable>
<xsl:variable name='gotopage2'>Aller &#x00e0; la page 2</xsl:variable>
<xsl:variable name='gotopage3'>Aller &#x00e0; la page 3</xsl:variable>
<xsl:variable name='gotopage4'>Aller &#x00e0; la page 4</xsl:variable>
<xsl:variable name='gotopage5'>Aller &#x00e0; la page 5</xsl:variable>
<xsl:variable name='gotopage6'>Aller &#x00e0; la page 6</xsl:variable>
<xsl:variable name='gotopage7'>Aller &#x00e0; la page 7</xsl:variable>
<xsl:variable name='gotopage8'>Aller &#x00e0; la page 8</xsl:variable>
<xsl:variable name='gotopage9'>Aller &#x00e0; la page 9</xsl:variable>
<xsl:variable name='gotopage10'>Aller &#x00e0; la page 10</xsl:variable>
<xsl:variable name='refresh'>Rafra&#x00ee;chir</xsl:variable>
<xsl:variable name='status'>&#x00c9;tat</xsl:variable>
<xsl:variable name='togglefilters'>Modifier l'affichage des filtres</xsl:variable>
<xsl:variable name='itemsselected'>&#x00e9;l&#x00e9;ments s&#x00e9;lectionn&#x00e9;s</xsl:variable>
<xsl:variable name='bulkvisible'>Les xxx rang&#x00e9;es visibles sont s&#x00e9;lectionn&#x00e9;es.</xsl:variable>
<xsl:variable name='bulktotal'>S&#x00e9;lectionner toutes les rang&#x00e9;es (xxx)</xsl:variable>
<xsl:variable name='informationalmessage'>Message informatif</xsl:variable>
<xsl:variable name='criticalerrormessage'>Message d'erreur critique</xsl:variable>
<xsl:variable name='errormessage'>Message d'erreur</xsl:variable>
<xsl:variable name='warningmessage'>Message d'avertissement</xsl:variable>
<xsl:variable name='successmessage'>Message de r&#x00e9;ussite</xsl:variable>
<xsl:variable name='alert'>Alerte</xsl:variable>
<xsl:variable name='confirm'>Confirmer</xsl:variable>
<xsl:variable name='prompt'>Inviter</xsl:variable>
<xsl:variable name='yes'>Oui</xsl:variable>
<xsl:variable name='no'>Non</xsl:variable>
<xsl:variable name='expandwindow'>D&#x00e9;velopper la fen&#x00ea;tre pour afficher d'autres &#x00e9;l&#x00e9;ments</xsl:variable>
<xsl:variable name='messagenumber'>Nombre de messages</xsl:variable>
<xsl:variable name='rssfeed'>Flux RSS</xsl:variable>
</xsl:stylesheet>
