<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:variable name='logout'>Oturumu Kapat</xsl:variable>
<xsl:variable name='about'>Hakk&#x0131;nda</xsl:variable>
<xsl:variable name='msgInvalidData'>Ge&#x00e7;ersiz veri girildi</xsl:variable>
<xsl:variable name='msgInvalidData.ipv4'>Ge&#x00e7;erli bir IPv4 adresi, noktalarla ayr&#x0131;lm&#x0131;&#x015f; d&#x00f6;rt rakamdan (0-255) olu&#x015f;ur, &#x00f6;rn. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.netmask'>Ge&#x00e7;erli bir a&#x011f; maskesi, noktalarla ayr&#x0131;lm&#x0131;&#x015f; d&#x00f6;rt rakamdan (0-255-) olu&#x015f;ur, &#x00f6;rn. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.mac'>Ge&#x00e7;erli bir MAC adresi nn:nn:nn:nn:nn:nn &#x015f;eklindedir ve 'n' ise, ya rakam (0-9) ya da harftir (A-F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6'>Ge&#x00e7;erli bir IPv6 adresi n:n:n:n:n:n:n:n bi&#x00e7;imindedir ve 'n'lerin yerine rakamlar (0-9) veya harfler (A-F) gelir</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6mask'>Ge&#x00e7;ersiz veri girildi</xsl:variable>
<xsl:variable name='msgInvalidData.time2'>Girilen zaman, 1:00 ile 12:59 aral&#x0131;&#x011f;&#x0131;nda olmal&#x0131;d&#x0131;r</xsl:variable>
<xsl:variable name='msgInvalidData.miltime2'>Girilen zaman, 0:00 ile 23:59 aral&#x0131;&#x011f;&#x0131;nda olmal&#x0131;d&#x0131;r</xsl:variable>
<xsl:variable name='msgNoncontiguousReorder'>Sadece biti&#x015f;ik olan se&#x00e7;ili s&#x0131;ralar&#x0131; yeniden s&#x0131;ralayabilirsiniz</xsl:variable>
<xsl:variable name='msgStepHasErrors'>Sihirbaz ad&#x0131;m&#x0131;, 1 veya daha fazla hata i&#x00e7;erir</xsl:variable>
<xsl:variable name='msgTabHasErrors'>Sekme, 1 veya daha fazla hata i&#x00e7;erir</xsl:variable>
<xsl:variable name='rowsperpage'>Sayfa ba&#x015f;&#x0131;na s&#x0131;ra</xsl:variable>
<xsl:variable name='perpage'>sayfa ba&#x015f;&#x0131;na</xsl:variable>
<xsl:variable name='itemsperpage'>Sayfa ba&#x015f;&#x0131;na nesne</xsl:variable>
<xsl:variable name='page'></xsl:variable>
<xsl:variable name='of'>Sayfa</xsl:variable>
<xsl:variable name='go'>Git</xsl:variable>
<xsl:variable name='setall'>T&#x00fc;m&#x00fc;n&#x00fc; Se&#x00e7;</xsl:variable>
<xsl:variable name='clearall'>T&#x00fc;m&#x00fc;n&#x00fc; Temizle</xsl:variable>
<xsl:variable name='undoall'>T&#x00fc;m&#x00fc;n&#x00fc; Geri Al</xsl:variable>
<xsl:variable name='sun'>Paz</xsl:variable>
<xsl:variable name='mon'>Pzt</xsl:variable>
<xsl:variable name='tue'>Sal</xsl:variable>
<xsl:variable name='wed'>&#x00c7;ar</xsl:variable>
<xsl:variable name='thu'>Per</xsl:variable>
<xsl:variable name='fri'>Cum</xsl:variable>
<xsl:variable name='sat'>Cts</xsl:variable>
<xsl:variable name='login'>Oturum A&#x00e7;</xsl:variable>
<xsl:variable name='submit'>G&#x00f6;nder</xsl:variable>
<xsl:variable name='reset'>S&#x0131;f&#x0131;rla</xsl:variable>
<xsl:variable name='filter'>Filtre</xsl:variable>
<xsl:variable name='matchif'>E&#x015f;le&#x015f;tir</xsl:variable>
<xsl:variable name='matchgo'>Git</xsl:variable>
<xsl:variable name='matchclear'>Filtre Temizle</xsl:variable>
<xsl:variable name='matchcontains'>&#x015e;unu i&#x00e7;erir</xsl:variable>
<xsl:variable name='matchnotcontain'>&#x015e;unu i&#x00e7;ermez</xsl:variable>
<xsl:variable name='matchstartswith'>&#x015e;ununla ba&#x015f;lar</xsl:variable>
<xsl:variable name='matchendswith'>&#x015e;ununla biter</xsl:variable>
<xsl:variable name='matchexactly'>Kesinlikle &#x015f;&#x00f6;yledir</xsl:variable>
<xsl:variable name='matchnotexactly'>De&#x011f;ildir</xsl:variable>
<xsl:variable name='matchempty'>Bo&#x015f;</xsl:variable>
<xsl:variable name='matchnotempty'>Bo&#x015f; de&#x011f;il</xsl:variable>
<xsl:variable name='matchistrue'>Do&#x011f;ru</xsl:variable>
<xsl:variable name='matchisfalse'>Yanl&#x0131;&#x015f;</xsl:variable>
<xsl:variable name='matchgreater'>&#x015e;undan b&#x00fc;y&#x00fc;kt&#x00fc;r</xsl:variable>
<xsl:variable name='matchgreaterequal'>&#x015e;undan b&#x00fc;y&#x00fc;kt&#x00fc;r ya da ona e&#x015f;ittir</xsl:variable>
<xsl:variable name='matchless'>&#x015e;undan k&#x00fc;&#x00e7;&#x00fc;kt&#x00fc;r</xsl:variable>
<xsl:variable name='matchlessequal'>&#x015e;undan k&#x00fc;&#x00e7;&#x00fc;kt&#x00fc;r ya da ona e&#x015f;ittir</xsl:variable>
<xsl:variable name='matchequal'>&#x015e;una e&#x015f;ittir</xsl:variable>
<xsl:variable name='matchnotequal'>&#x015e;una e&#x015f;it de&#x011f;ildir</xsl:variable>
<xsl:variable name='matchafter'>&#x015e;undan sonrad&#x0131;r</xsl:variable>
<xsl:variable name='matchafterequal'>&#x015e;undan sonrad&#x0131;r ya da ona e&#x015f;ittir</xsl:variable>
<xsl:variable name='matchbefore'>&#x015e;undan &#x00f6;ncedir</xsl:variable>
<xsl:variable name='matchbeforeequal'>&#x015e;undan &#x00f6;ncedir ya da ona e&#x015f;ittir</xsl:variable>
<xsl:variable name='sortclue'>S&#x0131;ralamak i&#x00e7;in t&#x0131;klay&#x0131;n</xsl:variable>
<xsl:variable name='special'>&#x00d6;zel</xsl:variable>
<xsl:variable name='blocked'>Engellenen G&#x00fc;n</xsl:variable>
<xsl:variable name='today'>Bug&#x00fc;n</xsl:variable>
<xsl:variable name='jan'>Oca</xsl:variable>
<xsl:variable name='feb'>&#x015e;ub</xsl:variable>
<xsl:variable name='mar'>Mar</xsl:variable>
<xsl:variable name='apr'>Nis</xsl:variable>
<xsl:variable name='may'>May</xsl:variable>
<xsl:variable name='jun'>Haz</xsl:variable>
<xsl:variable name='jul'>Tem</xsl:variable>
<xsl:variable name='aug'>A&#x011f;u</xsl:variable>
<xsl:variable name='sep'>Eyl</xsl:variable>
<xsl:variable name='oct'>Eki</xsl:variable>
<xsl:variable name='nov'>Kas</xsl:variable>
<xsl:variable name='dec'>Ara</xsl:variable>
<xsl:variable name='navigation'>Dola&#x015f;&#x0131;m</xsl:variable>
<xsl:variable name='items'>Nesneler</xsl:variable>
<xsl:variable name='showing'>G&#x00f6;sterilen</xsl:variable>
<xsl:variable name='back'>Geri</xsl:variable>
<xsl:variable name='next'>&#x0130;leri</xsl:variable>
<xsl:variable name='previous'>&#x00d6;nceki</xsl:variable>
<xsl:variable name='help'>Yard&#x0131;m</xsl:variable>
<xsl:variable name='cancel'>&#x0130;ptal</xsl:variable>
<xsl:variable name='ok'>Tamam</xsl:variable>
<xsl:variable name='movetotop'>En &#x00dc;ste Ta&#x015f;&#x0131; D&#x00fc;&#x011f;mesi - Se&#x00e7;ili &#x00f6;&#x011f;eyi Se&#x00e7;ilen Listesi'nin en &#x00fc;st&#x00fc;ne ta&#x015f;&#x0131;r</xsl:variable>
<xsl:variable name='movetobottom'>En Alta Ta&#x015f;&#x0131; D&#x00fc;&#x011f;mesi - Se&#x00e7;ili &#x00f6;&#x011f;eyi Se&#x00e7;ilen Listesi'nin en sonuna ta&#x015f;&#x0131;r</xsl:variable>
<xsl:variable name='moveup'>Yukar&#x0131; Ta&#x015f;&#x0131; D&#x00fc;&#x011f;mesi - Se&#x00e7;ili &#x00f6;&#x011f;eyi Se&#x00e7;ilen Listesi'nde bir s&#x0131;ra yukar&#x0131; ta&#x015f;&#x0131;r</xsl:variable>
<xsl:variable name='movedown'>A&#x015f;a&#x011f;&#x0131; Ta&#x015f;&#x0131; D&#x00fc;&#x011f;mesi - Se&#x00e7;ili &#x00f6;&#x011f;eyi Se&#x00e7;ilen Listesi'nde bir s&#x0131;ra a&#x015f;a&#x011f;&#x0131; ta&#x015f;&#x0131;r</xsl:variable>
<xsl:variable name='moveright'>Se&#x00e7; D&#x00fc;&#x011f;mesi - Se&#x00e7;ili &#x00f6;&#x011f;eyi Kullan&#x0131;labilir Kutusu'ndan Se&#x00e7;ilen Kutusu'na ta&#x015f;&#x0131;r</xsl:variable>
<xsl:variable name='moveallright'>T&#x00fc;m&#x00fc;n&#x00fc; Se&#x00e7; D&#x00fc;&#x011f;mesi - Kullan&#x0131;labilir Kutusu'ndaki t&#x00fc;m &#x00f6;&#x011f;eleri se&#x00e7;er</xsl:variable>
<xsl:variable name='moveleft'>Se&#x00e7;imi Kald&#x0131;r D&#x00fc;&#x011f;mesi - Se&#x00e7;ili &#x00f6;&#x011f;eyi Kullan&#x0131;labilir Kutusu'ndan kald&#x0131;r&#x0131;r</xsl:variable>
<xsl:variable name='moveallleft'>T&#x00fc;m Se&#x00e7;imleri Kald&#x0131;r - T&#x00fc;m &#x00f6;&#x011f;eleri Se&#x00e7;ilen Kutusu'ndan kald&#x0131;r&#x0131;r</xsl:variable>
<xsl:variable name='showchoices'>Tercih edilenleri g&#x00f6;ster</xsl:variable>
<xsl:variable name='sortascending'>Artan s&#x0131;rala</xsl:variable>
<xsl:variable name='sortdescending'>Azalan s&#x0131;rala</xsl:variable>
<xsl:variable name='scrollup'>Yukar&#x0131; git</xsl:variable>
<xsl:variable name='scrolldown'>A&#x015f;a&#x011f;&#x0131; git</xsl:variable>
<xsl:variable name='expanddrawer'>Geni&#x015f;let</xsl:variable>
<xsl:variable name='collapsedrawer'>Daralt</xsl:variable>
<xsl:variable name='collapsenav'>Dola&#x015f;&#x0131;m Penceresini Daralt</xsl:variable>
<xsl:variable name='expandnav'>Dola&#x015f;&#x0131;m Penceresini Geni&#x015f;let</xsl:variable>
<xsl:variable name='resizenav'>Dola&#x015f;&#x0131;m Penceresini Yeniden Boyutland&#x0131;r</xsl:variable>
<xsl:variable name='resizetaskpane'>G&#x00f6;rev Panelini Yeniden Boyutland&#x0131;r</xsl:variable>
<xsl:variable name='spinner'>&#x0130;lgili de&#x011f;eri art&#x0131;r/azalat</xsl:variable>
<xsl:variable name='firstpage'>&#x0130;lk sayfa</xsl:variable>
<xsl:variable name='previouspage'>&#x00d6;nceki sayfa</xsl:variable>
<xsl:variable name='nextpage'>Sonraki sayfa</xsl:variable>
<xsl:variable name='lastpage'>Son sayfa</xsl:variable>
<xsl:variable name='singlerowselection'>tekli s&#x0131;ra se&#x00e7;imi</xsl:variable>
<xsl:variable name='multiplerowselection'>&#x00e7;oklu s&#x0131;ra se&#x00e7;imi</xsl:variable>
<xsl:variable name='allrowselection'>T&#x00fc;m sat&#x0131;rlar se&#x00e7;</xsl:variable>
<xsl:variable name='increaseindentation'>Girinti art&#x0131;r</xsl:variable>
<xsl:variable name='decreaseindentation'>Girinti azalt</xsl:variable>
<xsl:variable name='leaf'>Yaprak</xsl:variable>
<xsl:variable name='expandtree'>A&#x011f;a&#x00e7; nesnesini geni&#x015f;let</xsl:variable>
<xsl:variable name='collapsetree'>A&#x011f;a&#x00e7; nesnesini daralt</xsl:variable>
<xsl:variable name='togglepane'>Pencere durumuna ge&#x00e7;</xsl:variable>
<xsl:variable name='closepane'>Pencere kapat</xsl:variable>
<xsl:variable name='msgRequiredField'>Gerekli alan</xsl:variable>
<xsl:variable name='msgRequiredFieldsNotice'>Gerekli alanlar</xsl:variable>
<xsl:variable name='moveto_move'>Ta&#x015f;&#x0131;</xsl:variable>
<xsl:variable name='moveto_above'>Yukar&#x0131;</xsl:variable>
<xsl:variable name='moveto_below'>A&#x015f;a&#x011f;&#x0131;</xsl:variable>
<xsl:variable name='moveto_rownum'>S&#x0131;ra numaras&#x0131;</xsl:variable>
<xsl:variable name='moveto_moveto'>Ta&#x015f;&#x0131;</xsl:variable>
<xsl:variable name='applynew'>Yeni uygula</xsl:variable>
<xsl:variable name='emptyrow'>G&#x00f6;r&#x00fc;nt&#x00fc;lenecek veri yok</xsl:variable>
<xsl:variable name='more'>daha</xsl:variable>
<xsl:variable name='less'>az</xsl:variable>
<xsl:variable name='loading'>Y&#x00fc;kl&#x00fc;yor...</xsl:variable>
<xsl:variable name='moveabsolute'>Se&#x00e7;ileni &#x00f6;zel konuma ta&#x015f;&#x0131;</xsl:variable>
<xsl:variable name='showdatepicker'>Tarih g&#x00f6;r&#x00fc;nt&#x00fc;leyiciyi g&#x00f6;ster</xsl:variable>
<xsl:variable name='showpreviousmonth'>&#x00d6;nceki ay&#x0131; g&#x00f6;ster</xsl:variable>
<xsl:variable name='shownextmonth'>Sonraki ay&#x0131; g&#x00f6;ster</xsl:variable>
<xsl:variable name='msgVerifyingLogin'>Do&#x011f;ruluyor</xsl:variable>
<xsl:variable name='all'>T&#x00fc;m&#x00fc;</xsl:variable>
<xsl:variable name='msgReorderError'>Belirtilen s&#x0131;ra numaras&#x0131; mevcut de&#x011f;il</xsl:variable>
<xsl:variable name='currentpasswordprompt'>Mevcut &#x015e;ifreyi Gir</xsl:variable>
<xsl:variable name='newpasswordprompt'>Yeni &#x015e;ifreyi Gir</xsl:variable>
<xsl:variable name='confirmpasswordprompt'>Yeni &#x015e;ifreyi Tekrar Gir</xsl:variable>
<xsl:variable name='save'>Kaydet</xsl:variable>
<xsl:variable name='newwindow'>Yeni pencerede a&#x00e7;</xsl:variable>
<xsl:variable name='gettingstarted'>Ba&#x015f;larken</xsl:variable>
<xsl:variable name='donotshowagain'>Tekrar g&#x00f6;sterme</xsl:variable>
<xsl:variable name='companylogo'>Cisco logosu</xsl:variable>
<xsl:variable name='results'>sonu&#x00e7;lar</xsl:variable>
<xsl:variable name='editthismodule'>Bu mod&#x00fc;l&#x00fc; d&#x00fc;zenle</xsl:variable>
<xsl:variable name='remove'>Kald&#x0131;r</xsl:variable>
<xsl:variable name='loginproblem'>Oturum a&#x00e7;arken sorun mu ya&#x015f;&#x0131;yorsunuz?</xsl:variable>
<xsl:variable name='expandpane'>Geni&#x015f;let</xsl:variable>
<xsl:variable name='collapsepane'>Daralt</xsl:variable>
<xsl:variable name='restorepane'>Geri Y&#x00fc;kle</xsl:variable>
<xsl:variable name='dateselectionmonth'>Tarih se&#x00e7;imi - ay</xsl:variable>
<xsl:variable name='dateselectionday'>Tarih se&#x00e7;imi - g&#x00fc;n</xsl:variable>
<xsl:variable name='dateselectionyear'>Tarih se&#x00e7;imi - y&#x0131;l</xsl:variable>
<xsl:variable name='timeselectionhour'>Tarih se&#x00e7;imi - saat</xsl:variable>
<xsl:variable name='timeselectionminute'>Tarih se&#x00e7;imi - dakika</xsl:variable>
<xsl:variable name='timeselectionampm'>Tarih se&#x00e7;imi - AM veya PM</xsl:variable>
<xsl:variable name='and'>ve</xsl:variable>
<xsl:variable name='or'>veya</xsl:variable>
<xsl:variable name='addfilter'>Filtre ekle</xsl:variable>
<xsl:variable name='removefilter'>Filtreyi kald&#x0131;r</xsl:variable>
<xsl:variable name='filterrelationship'>Filtre ili&#x015f;kisi</xsl:variable>
<xsl:variable name='signin'>Oturum A&#x00e7;</xsl:variable>
<xsl:variable name='signout'>Oturumu Kapat</xsl:variable>
<xsl:variable name='submenu'>Alt Men&#x00fc;</xsl:variable>
<xsl:variable name='gotopage1'>1. sayfaya git</xsl:variable>
<xsl:variable name='gotopage2'>2. sayfaya git</xsl:variable>
<xsl:variable name='gotopage3'>3. sayfaya git</xsl:variable>
<xsl:variable name='gotopage4'>4. sayfaya git</xsl:variable>
<xsl:variable name='gotopage5'>5. sayfaya git</xsl:variable>
<xsl:variable name='gotopage6'>6. sayfaya git</xsl:variable>
<xsl:variable name='gotopage7'>7. sayfaya git</xsl:variable>
<xsl:variable name='gotopage8'>8. sayfaya git</xsl:variable>
<xsl:variable name='gotopage9'>9. sayfaya git</xsl:variable>
<xsl:variable name='gotopage10'>10. sayfaya git</xsl:variable>
<xsl:variable name='refresh'>Yenile</xsl:variable>
<xsl:variable name='status'>Durum</xsl:variable>
<xsl:variable name='togglefilters'>Filtre g&#x00f6;r&#x00fc;n&#x00fc;m&#x00fc;n&#x00fc; de&#x011f;i&#x015f;tir</xsl:variable>
<xsl:variable name='itemsselected'>&#x00f6;&#x011f;e se&#x00e7;ildi</xsl:variable>
<xsl:variable name='bulkvisible'>G&#x00f6;r&#x00fc;lebilir xxx sat&#x0131;r&#x0131;n t&#x00fc;m&#x00fc; se&#x00e7;ildi.</xsl:variable>
<xsl:variable name='bulktotal'>xxx sat&#x0131;r&#x0131;n t&#x00fc;m&#x00fc;n&#x00fc; se&#x00e7;</xsl:variable>
<xsl:variable name='informationalmessage'>Bilgi mesaj&#x0131;</xsl:variable>
<xsl:variable name='criticalerrormessage'>Kritik hata mesaj&#x0131;</xsl:variable>
<xsl:variable name='errormessage'>Hata mesaj&#x0131;</xsl:variable>
<xsl:variable name='warningmessage'>Uyar&#x0131; mesaj&#x0131;</xsl:variable>
<xsl:variable name='successmessage'>Ba&#x015f;ar&#x0131;l&#x0131; mesaj&#x0131;</xsl:variable>
<xsl:variable name='alert'>Uyar&#x0131;</xsl:variable>
<xsl:variable name='confirm'>Onayla</xsl:variable>
<xsl:variable name='prompt'>Sor</xsl:variable>
<xsl:variable name='yes'>Evet</xsl:variable>
<xsl:variable name='no'>Hay&#x0131;r</xsl:variable>
<xsl:variable name='expandwindow'>Di&#x011f;er &#x00f6;&#x011f;eleri g&#x00f6;rmek i&#x00e7;in pencereyi geni&#x015f;let</xsl:variable>
<xsl:variable name='messagenumber'>Mesaj Numaras&#x0131;</xsl:variable>
<xsl:variable name='rssfeed'>RSS ak&#x0131;&#x015f;&#x0131;</xsl:variable>
</xsl:stylesheet>
