<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:variable name='logout'>Odhl&#x00e1;sit</xsl:variable>
<xsl:variable name='about'>O&#x00a0;aplikaci</xsl:variable>
<xsl:variable name='msgInvalidData'>Byla zad&#x00e1;na neplatn&#x00e1; data</xsl:variable>
<xsl:variable name='msgInvalidData.ipv4'>Platn&#x00e1; adresa IPv4 se skl&#x00e1;d&#x00e1; ze &#x010d;ty&#x0159; &#x010d;&#x00ed;sel (0 a&#x017e; 255) odd&#x011b;len&#x00fd;ch te&#x010d;kou, nap&#x0159;. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.netmask'>Platn&#x00e1; maska s&#x00ed;t&#x011b; se skl&#x00e1;d&#x00e1; ze &#x010d;ty&#x0159; &#x010d;&#x00ed;sel (0 a&#x017e; 255) odd&#x011b;len&#x00fd;ch te&#x010d;kou, nap&#x0159;. 123.0.255.3</xsl:variable>
<xsl:variable name='msgInvalidData.mac'>Platn&#x00e1; adresa MAC je ve tvaru nn:nn:nn:nn:nn:nn, kde nam&#x00ed;sto p&#x00ed;smen &#x201e;n&#x201c; jsou &#x010d;&#x00ed;slice (0 a&#x017e; 9) nebo p&#x00ed;smena (A a&#x017e; F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6'>Platn&#x00e1; adresa IPv6 je ve tvaru n:n:n:n:n:n:n:n, kde nam&#x00ed;sto p&#x00ed;smen &#x201e;n&#x201c; jsou &#x010d;&#x00ed;slice (0 a&#x017e; 9) nebo p&#x00ed;smena (A a&#x017e; F)</xsl:variable>
<xsl:variable name='msgInvalidData.ipv6mask'>Byla zad&#x00e1;na neplatn&#x00e1; data</xsl:variable>
<xsl:variable name='msgInvalidData.time2'>Zadan&#x00fd; &#x010d;as mus&#x00ed; b&#x00fd;t v&#x00a0;rozsahu od 1:00 do 12:59</xsl:variable>
<xsl:variable name='msgInvalidData.miltime2'>Zadan&#x00fd; &#x010d;as mus&#x00ed; b&#x00fd;t v&#x00a0;rozsahu od 0:00 do 23:59</xsl:variable>
<xsl:variable name='msgNoncontiguousReorder'>M&#x016f;&#x017e;ete m&#x011b;nit po&#x0159;ad&#x00ed; pouze t&#x011b;ch vybran&#x00fd;ch &#x0159;&#x00e1;dk&#x016f;, kter&#x00e9; spolu soused&#x00ed;</xsl:variable>
<xsl:variable name='msgStepHasErrors'>Krok pr&#x016f;vodce obsahuje 1 nebo v&#x00ed;ce chyb</xsl:variable>
<xsl:variable name='msgTabHasErrors'>Tabulka obsahuje 1 nebo v&#x00ed;ce chyb</xsl:variable>
<xsl:variable name='rowsperpage'>&#x0158;&#x00e1;dk&#x016f; na stranu</xsl:variable>
<xsl:variable name='perpage'>na stranu</xsl:variable>
<xsl:variable name='itemsperpage'>Polo&#x017e;ek na stranu</xsl:variable>
<xsl:variable name='page'>Strana</xsl:variable>
<xsl:variable name='of'>z</xsl:variable>
<xsl:variable name='go'>P&#x0159;ej&#x00ed;t na</xsl:variable>
<xsl:variable name='setall'>Vybrat v&#x0161;e</xsl:variable>
<xsl:variable name='clearall'>Vymazat v&#x0161;e</xsl:variable>
<xsl:variable name='undoall'>Vr&#x00e1;tit v&#x0161;e</xsl:variable>
<xsl:variable name='sun'>Ne</xsl:variable>
<xsl:variable name='mon'>Po</xsl:variable>
<xsl:variable name='tue'>&#x00da;t</xsl:variable>
<xsl:variable name='wed'>St</xsl:variable>
<xsl:variable name='thu'>&#x010c;t</xsl:variable>
<xsl:variable name='fri'>P&#x00e1;</xsl:variable>
<xsl:variable name='sat'>So</xsl:variable>
<xsl:variable name='login'>P&#x0159;ihl&#x00e1;sit</xsl:variable>
<xsl:variable name='submit'>Odeslat</xsl:variable>
<xsl:variable name='reset'>Obnovit p&#x016f;vodn&#x00ed;</xsl:variable>
<xsl:variable name='filter'>Filtr</xsl:variable>
<xsl:variable name='matchif'>Odpov&#x00ed;d&#x00e1;, pokud</xsl:variable>
<xsl:variable name='matchgo'>P&#x0159;ej&#x00ed;t na</xsl:variable>
<xsl:variable name='matchclear'>Vynulovat filtr</xsl:variable>
<xsl:variable name='matchcontains'>Obsahuje</xsl:variable>
<xsl:variable name='matchnotcontain'>Neobsahuje</xsl:variable>
<xsl:variable name='matchstartswith'>Za&#x010d;&#x00ed;n&#x00e1; na</xsl:variable>
<xsl:variable name='matchendswith'>Kon&#x010d;&#x00ed; na</xsl:variable>
<xsl:variable name='matchexactly'>Je p&#x0159;esn&#x011b;</xsl:variable>
<xsl:variable name='matchnotexactly'>Nen&#x00ed;</xsl:variable>
<xsl:variable name='matchempty'>Je pr&#x00e1;zdn&#x00e9;</xsl:variable>
<xsl:variable name='matchnotempty'>Nen&#x00ed; pr&#x00e1;zdn&#x00e9;</xsl:variable>
<xsl:variable name='matchistrue'>Je pravda</xsl:variable>
<xsl:variable name='matchisfalse'>Nen&#x00ed; pravda</xsl:variable>
<xsl:variable name='matchgreater'>Je v&#x011b;t&#x0161;&#x00ed; ne&#x017e;</xsl:variable>
<xsl:variable name='matchgreaterequal'>Je v&#x011b;t&#x0161;&#x00ed; nebo se rovn&#x00e1;</xsl:variable>
<xsl:variable name='matchless'>Je men&#x0161;&#x00ed; ne&#x017e;</xsl:variable>
<xsl:variable name='matchlessequal'>Je men&#x0161;&#x00ed; nebo se rovn&#x00e1;</xsl:variable>
<xsl:variable name='matchequal'>Rovn&#x00e1; se</xsl:variable>
<xsl:variable name='matchnotequal'>Nerovn&#x00e1; se</xsl:variable>
<xsl:variable name='matchafter'>N&#x00e1;sleduje po</xsl:variable>
<xsl:variable name='matchafterequal'>N&#x00e1;sleduje po nebo se rovn&#x00e1;</xsl:variable>
<xsl:variable name='matchbefore'>P&#x0159;edch&#x00e1;z&#x00ed;</xsl:variable>
<xsl:variable name='matchbeforeequal'>P&#x0159;edch&#x00e1;z&#x00ed; nebo se rovn&#x00e1;</xsl:variable>
<xsl:variable name='sortclue'>Se&#x0159;adit kliknut&#x00ed;m</xsl:variable>
<xsl:variable name='special'>Zvl&#x00e1;&#x0161;tn&#x00ed;</xsl:variable>
<xsl:variable name='blocked'>Blokovan&#x00fd; den</xsl:variable>
<xsl:variable name='today'>Dnes</xsl:variable>
<xsl:variable name='jan'>Led</xsl:variable>
<xsl:variable name='feb'>&#x00da;no</xsl:variable>
<xsl:variable name='mar'>B&#x0159;e</xsl:variable>
<xsl:variable name='apr'>Dub</xsl:variable>
<xsl:variable name='may'>Kv&#x011b;</xsl:variable>
<xsl:variable name='jun'>&#x010c;er</xsl:variable>
<xsl:variable name='jul'>&#x010c;ec</xsl:variable>
<xsl:variable name='aug'>Srp</xsl:variable>
<xsl:variable name='sep'>Z&#x00e1;&#x0159;</xsl:variable>
<xsl:variable name='oct'>&#x0158;&#x00ed;j</xsl:variable>
<xsl:variable name='nov'>Lis</xsl:variable>
<xsl:variable name='dec'>Pro</xsl:variable>
<xsl:variable name='navigation'>Navigace</xsl:variable>
<xsl:variable name='items'>Polo&#x017e;ky</xsl:variable>
<xsl:variable name='showing'>Zobrazeno</xsl:variable>
<xsl:variable name='back'>Zp&#x011b;t</xsl:variable>
<xsl:variable name='next'>Dal&#x0161;&#x00ed;</xsl:variable>
<xsl:variable name='previous'>P&#x0159;edchoz&#x00ed;</xsl:variable>
<xsl:variable name='help'>N&#x00e1;pov&#x011b;da</xsl:variable>
<xsl:variable name='cancel'>Zru&#x0161;it</xsl:variable>
<xsl:variable name='ok'>OK</xsl:variable>
<xsl:variable name='movetotop'>Tla&#x010d;&#x00ed;tko Na za&#x010d;&#x00e1;tek&#x00a0;&#x2013; P&#x0159;esune pr&#x00e1;v&#x011b; vybranou polo&#x017e;ku na za&#x010d;&#x00e1;tek vybran&#x00e9;ho seznamu</xsl:variable>
<xsl:variable name='movetobottom'>Tla&#x010d;&#x00ed;tko Na konec&#x00a0;&#x2013; P&#x0159;esune pr&#x00e1;v&#x011b; vybranou polo&#x017e;ku na konec vybran&#x00e9;ho seznamu</xsl:variable>
<xsl:variable name='moveup'>Tla&#x010d;&#x00ed;tko Nahoru&#x00a0;&#x2013; P&#x0159;esune pr&#x00e1;v&#x011b; vybranou polo&#x017e;ku o&#x00a0;jedno m&#x00ed;sto nahoru ve vybran&#x00e9;m seznamu</xsl:variable>
<xsl:variable name='movedown'>Tla&#x010d;&#x00ed;tko Dol&#x016f;&#x00a0;&#x2013; P&#x0159;esune pr&#x00e1;v&#x011b; vybranou polo&#x017e;ku o&#x00a0;jedno m&#x00ed;sto dol&#x016f; ve vybran&#x00e9;m seznamu</xsl:variable>
<xsl:variable name='moveright'>Tla&#x010d;&#x00ed;tko Vybrat&#x00a0;&#x2013; P&#x0159;esune pr&#x00e1;v&#x011b; vybranou polo&#x017e;ku z&#x00a0;kolonky Dostupn&#x00e9; do kolonky Vybran&#x00e9;</xsl:variable>
<xsl:variable name='moveallright'>Tla&#x010d;&#x00ed;tko Vybrat v&#x0161;e&#x00a0;&#x2013; Vybere v&#x0161;echny polo&#x017e;ky v&#x00a0;kolonce Dostupn&#x00e9;</xsl:variable>
<xsl:variable name='moveleft'>Tla&#x010d;&#x00ed;tko Odzna&#x010d;it&#x00a0;&#x2013; Odebere pr&#x00e1;v&#x011b; vybranou polo&#x017e;ku z&#x00a0;kolonky Vybran&#x00e9;</xsl:variable>
<xsl:variable name='moveallleft'>Tla&#x010d;&#x00ed;tko Odzna&#x010d;it v&#x0161;e&#x00a0;&#x2013; Odebere v&#x0161;echny polo&#x017e;ky z&#x00a0;kolonky Vybran&#x00e9;</xsl:variable>
<xsl:variable name='showchoices'>Zobrazit v&#x00fd;b&#x011b;r</xsl:variable>
<xsl:variable name='sortascending'>&#x0158;adit vzestupn&#x011b;</xsl:variable>
<xsl:variable name='sortdescending'>&#x0158;adit sestupn&#x011b;</xsl:variable>
<xsl:variable name='scrollup'>Posunout nahoru</xsl:variable>
<xsl:variable name='scrolldown'>Posunout dol&#x016f;</xsl:variable>
<xsl:variable name='expanddrawer'>Rozbalit</xsl:variable>
<xsl:variable name='collapsedrawer'>Sbalit</xsl:variable>
<xsl:variable name='collapsenav'>Sbalit naviga&#x010d;n&#x00ed; panel</xsl:variable>
<xsl:variable name='expandnav'>Rozbalit naviga&#x010d;n&#x00ed; panel</xsl:variable>
<xsl:variable name='resizenav'>Zm&#x011b;nit velikost naviga&#x010d;n&#x00ed;ho panelu</xsl:variable>
<xsl:variable name='resizetaskpane'>Zm&#x011b;nit velikost panelu &#x00fa;loh</xsl:variable>
<xsl:variable name='spinner'>Zvy&#x0161;uje/sni&#x017e;uje souvisej&#x00ed;c&#x00ed; hodnotu</xsl:variable>
<xsl:variable name='firstpage'>Prvn&#x00ed; strana</xsl:variable>
<xsl:variable name='previouspage'>P&#x0159;edchoz&#x00ed; strana</xsl:variable>
<xsl:variable name='nextpage'>N&#x00e1;sleduj&#x00ed;c&#x00ed; strana</xsl:variable>
<xsl:variable name='lastpage'>Posledn&#x00ed; strana</xsl:variable>
<xsl:variable name='singlerowselection'>v&#x00fd;b&#x011b;r jednoho &#x0159;&#x00e1;dku</xsl:variable>
<xsl:variable name='multiplerowselection'>v&#x00fd;b&#x011b;r v&#x00ed;ce &#x0159;&#x00e1;dk&#x016f;</xsl:variable>
<xsl:variable name='allrowselection'>Vybrat v&#x0161;echny &#x0159;&#x00e1;dky</xsl:variable>
<xsl:variable name='increaseindentation'>Zv&#x011b;t&#x0161;it odsazen&#x00ed;</xsl:variable>
<xsl:variable name='decreaseindentation'>Zmen&#x0161;it odsazen&#x00ed;</xsl:variable>
<xsl:variable name='leaf'>List</xsl:variable>
<xsl:variable name='expandtree'>Rozbalit polo&#x017e;ku stromu</xsl:variable>
<xsl:variable name='collapsetree'>Sbalit polo&#x017e;ku stromu</xsl:variable>
<xsl:variable name='togglepane'>Zm&#x011b;nit stav panelu</xsl:variable>
<xsl:variable name='closepane'>Zav&#x0159;&#x00ed;t panel</xsl:variable>
<xsl:variable name='msgRequiredField'>Povinn&#x00e9; pole</xsl:variable>
<xsl:variable name='msgRequiredFieldsNotice'>Povinn&#x00e1; pole</xsl:variable>
<xsl:variable name='moveto_move'>P&#x0159;esunout</xsl:variable>
<xsl:variable name='moveto_above'>Nad</xsl:variable>
<xsl:variable name='moveto_below'>Pod</xsl:variable>
<xsl:variable name='moveto_rownum'>&#x010c;&#x00ed;slo &#x0159;&#x00e1;dku</xsl:variable>
<xsl:variable name='moveto_moveto'>P&#x0159;esunout do</xsl:variable>
<xsl:variable name='applynew'>Pou&#x017e;&#x00ed;t nov&#x00e9;</xsl:variable>
<xsl:variable name='emptyrow'>&#x017d;&#x00e1;dn&#x00e1; data</xsl:variable>
<xsl:variable name='more'>v&#x00ed;ce</xsl:variable>
<xsl:variable name='less'>m&#x00e9;n&#x011b;</xsl:variable>
<xsl:variable name='loading'>Na&#x010d;&#x00ed;t&#x00e1;n&#x00ed;...</xsl:variable>
<xsl:variable name='moveabsolute'>P&#x0159;esunout vybran&#x00e9; na ur&#x010d;en&#x00e9; m&#x00ed;sto</xsl:variable>
<xsl:variable name='showdatepicker'>Zobrazit kalend&#x00e1;&#x0159;</xsl:variable>
<xsl:variable name='showpreviousmonth'>Zobrazit p&#x0159;edchoz&#x00ed; m&#x011b;s&#x00ed;c</xsl:variable>
<xsl:variable name='shownextmonth'>Zobrazit dal&#x0161;&#x00ed; m&#x011b;s&#x00ed;c</xsl:variable>
<xsl:variable name='msgVerifyingLogin'>Ov&#x011b;&#x0159;ov&#x00e1;n&#x00ed;</xsl:variable>
<xsl:variable name='all'>V&#x0161;e</xsl:variable>
<xsl:variable name='msgReorderError'>Zadan&#x00e9; &#x010d;&#x00ed;slo &#x0159;&#x00e1;dku neexistuje</xsl:variable>
<xsl:variable name='currentpasswordprompt'>Zadat aktu&#x00e1;ln&#x00ed; heslo</xsl:variable>
<xsl:variable name='newpasswordprompt'>Zadat nov&#x00e9; heslo</xsl:variable>
<xsl:variable name='confirmpasswordprompt'>Znovu zadat nov&#x00e9; heslo</xsl:variable>
<xsl:variable name='save'>Ulo&#x017e;it</xsl:variable>
<xsl:variable name='newwindow'>Otev&#x0159;&#x00ed;t v&#x00a0;nov&#x00e9;m okn&#x011b;</xsl:variable>
<xsl:variable name='gettingstarted'>Za&#x010d;&#x00ed;n&#x00e1;me</xsl:variable>
<xsl:variable name='donotshowagain'>Ji&#x017e; nezobrazovat</xsl:variable>
<xsl:variable name='companylogo'>Logo Cisco</xsl:variable>
<xsl:variable name='results'>v&#x00fd;sledk&#x016f;</xsl:variable>
<xsl:variable name='editthismodule'>Upravit tento modul</xsl:variable>
<xsl:variable name='remove'>Odstranit</xsl:variable>
<xsl:variable name='loginproblem'>Probl&#x00e9;my p&#x0159;i p&#x0159;ihla&#x0161;ov&#x00e1;n&#x00ed;?</xsl:variable>
<xsl:variable name='expandpane'>Rozbalit</xsl:variable>
<xsl:variable name='collapsepane'>Sbalit</xsl:variable>
<xsl:variable name='restorepane'>Obnovit</xsl:variable>
<xsl:variable name='dateselectionmonth'>Datum&#x00a0;&#x2013; volba m&#x011b;s&#x00ed;ce</xsl:variable>
<xsl:variable name='dateselectionday'>Datum&#x00a0;&#x2013; volba dne</xsl:variable>
<xsl:variable name='dateselectionyear'>Datum&#x00a0;&#x2013; volba roku</xsl:variable>
<xsl:variable name='timeselectionhour'>&#x010c;as&#x00a0;&#x2013; volba hodiny</xsl:variable>
<xsl:variable name='timeselectionminute'>&#x010c;as&#x00a0;&#x2013; volba minuty</xsl:variable>
<xsl:variable name='timeselectionampm'>&#x010c;as&#x00a0;&#x2013; volba AM nebo PM (dop./odp.)</xsl:variable>
<xsl:variable name='and'>a</xsl:variable>
<xsl:variable name='or'>nebo</xsl:variable>
<xsl:variable name='addfilter'>P&#x0159;idat filtr</xsl:variable>
<xsl:variable name='removefilter'>Odstranit filtr</xsl:variable>
<xsl:variable name='filterrelationship'>Vztah filtr&#x016f;</xsl:variable>
<xsl:variable name='signin'>P&#x0159;ihl&#x00e1;sit</xsl:variable>
<xsl:variable name='signout'>Odhl&#x00e1;sit</xsl:variable>
<xsl:variable name='submenu'>Podnab&#x00ed;dka</xsl:variable>
<xsl:variable name='gotopage1'>P&#x0159;ej&#x00ed;t na stranu&#x00a0;1</xsl:variable>
<xsl:variable name='gotopage2'>P&#x0159;ej&#x00ed;t na stranu&#x00a0;2</xsl:variable>
<xsl:variable name='gotopage3'>P&#x0159;ej&#x00ed;t na stranu&#x00a0;3</xsl:variable>
<xsl:variable name='gotopage4'>P&#x0159;ej&#x00ed;t na stranu&#x00a0;4</xsl:variable>
<xsl:variable name='gotopage5'>P&#x0159;ej&#x00ed;t na stranu&#x00a0;5</xsl:variable>
<xsl:variable name='gotopage6'>P&#x0159;ej&#x00ed;t na stranu&#x00a0;6</xsl:variable>
<xsl:variable name='gotopage7'>P&#x0159;ej&#x00ed;t na stranu&#x00a0;7</xsl:variable>
<xsl:variable name='gotopage8'>P&#x0159;ej&#x00ed;t na stranu&#x00a0;8</xsl:variable>
<xsl:variable name='gotopage9'>P&#x0159;ej&#x00ed;t na stranu&#x00a0;9</xsl:variable>
<xsl:variable name='gotopage10'>P&#x0159;ej&#x00ed;t na stranu&#x00a0;10</xsl:variable>
<xsl:variable name='refresh'>Aktualizovat</xsl:variable>
<xsl:variable name='status'>Stav</xsl:variable>
<xsl:variable name='togglefilters'>Zm&#x011b;nit zobrazen&#x00ed; filtr&#x016f;</xsl:variable>
<xsl:variable name='itemsselected'>vybran&#x00fd;ch polo&#x017e;ek</xsl:variable>
<xsl:variable name='bulkvisible'>Je vybr&#x00e1;no v&#x0161;ech xxx&#x00a0;viditeln&#x00fd;ch &#x0159;&#x00e1;dk&#x016f;.</xsl:variable>
<xsl:variable name='bulktotal'>Vybrat v&#x0161;ech xxx&#x00a0;&#x0159;&#x00e1;dk&#x016f;</xsl:variable>
<xsl:variable name='informationalmessage'>Informa&#x010d;n&#x00ed; zpr&#x00e1;va</xsl:variable>
<xsl:variable name='criticalerrormessage'>Zpr&#x00e1;va o&#x00a0;kritick&#x00e9; chyb&#x011b;</xsl:variable>
<xsl:variable name='errormessage'>Zpr&#x00e1;va o&#x00a0;chyb&#x011b;</xsl:variable>
<xsl:variable name='warningmessage'>Varovn&#x00e1; zpr&#x00e1;va</xsl:variable>
<xsl:variable name='successmessage'>Zpr&#x00e1;va o&#x00a0;&#x00fa;sp&#x011b;chu</xsl:variable>
<xsl:variable name='alert'>Upozorn&#x011b;n&#x00ed;</xsl:variable>
<xsl:variable name='confirm'>Potvrdit</xsl:variable>
<xsl:variable name='prompt'>Dot&#x00e1;zat</xsl:variable>
<xsl:variable name='yes'>Ano</xsl:variable>
<xsl:variable name='no'>Ne</xsl:variable>
<xsl:variable name='expandwindow'>Zv&#x011b;t&#x0161;it okno a zobrazit dal&#x0161;&#x00ed; polo&#x017e;ky</xsl:variable>
<xsl:variable name='messagenumber'>&#x010c;&#x00ed;slo zpr&#x00e1;vy</xsl:variable>
<xsl:variable name='rssfeed'>Kan&#x00e1;l RSS</xsl:variable>
</xsl:stylesheet>
